### ISSUE TITLE
Pokemon occupied slots

### ISSUE THREAD

**Issue by andremvm** [mtaheij/PoGo-UWP#10]
- Phone type: Lumia 640 DS
- App version: 1.2.4 beta

Steps to reproduce:

Open the Pokémon Menu

Actual behavior

It says that I currently have 42 pokemon slots used (out of 250), however I can only see 30, have no idea where the others are or which ones they are

Expected behavior

It should show the real amount of slots occupied or rather show the missing pokemons

Any idea why this is happening? Some limitation in the amount of pokemons that the app can show?

**Comment by ntaheij** [comment]
Did you count the eggs with the pokemons?

**Comment by andremvm** [comment]
Well, actually then it makes sense, all together is 42. Although I thought they would be separate because the eggs are not all being incubated at the moment and it shows 9/9 in their own slot. 

But then if this is the expected behaviour then you can close the issue, thanks! ;)

**Comment by ntaheij** [comment]
This is expected behaviour.
Eggs are counted as pokémons as well.
