### ISSUE TITLE
1 API Key for Two Accounts?

### ISSUE THREAD

**Issue by WanderingJesusFreak** [mtaheij/PoGo-UWP#11]
First, thank you for doing this. I'm sorry for the grief you are getting 
From people for "charging" for the API. Having been following this process from its inception, I understand the work you are doing and the fundamental difference between the API and your application.

That being said, my wife and I both have W10 phones. Can we use the same key for both, out does she need a separate one?

**Comment by ntaheij** [comment]
So far as I know, you need 2 keys for that.

**Comment by ntaheij** [comment]
Someone said you can do it with 1, but we didn't tested that yet.

**Comment by DarkLegend481** [comment]
You can, my brother and I use the same key.

**Comment by DarkLegend481** [comment]
But, try to not open at the same time...

**Comment by ntaheij** [comment]
Ok. If your "problem" is solved, say if i can close this issue

**Comment by WanderingJesusFreak** [comment]
Great. Thanks so much. Does it increases ban chances? I'll close this issue after that question is answered.

**Comment by BadiBasso** [comment]
I strongly don't think so. Hashing key is only used to access hashing service, it is not sent to Niantic in any form.

**Comment by mtaheij** [comment]
That is correct. The hashing key is totally unrelated to the requests that are sent to Niantic.
