### ISSUE TITLE
API Outdated

### ISSUE THREAD

**Issue by WanderingJesusFreak** [mtaheij/PoGo-UWP#111]
You probably know this already, but the API is outdated. Just figured I'd make an official issue.
![wp_ss_20170517_0001](https://cloud.githubusercontent.com/assets/21267490/26170464/86878be2-3b0f-11e7-9fae-ff1da29cc0d0.png)

**Comment by mtaheij** [comment]
Yes, I've seen it. Working on it. Tomorrow (hopefully), there will be a new version.

**Comment by WanderingJesusFreak** [comment]
Great. Thanks for all the work!

**Comment by DarkLegend481** [comment]
Hey, why we don't have a option like PokéBotNinja to disable the version check??

**Comment by Andy1210** [comment]
It has an option,
You can build it like that if you set the Configuration.IgnoreHashVersion to true

(it may increase the risk of account ban by niantic)
