### ISSUE TITLE
Small bug list

### ISSUE THREAD

**Issue by BadiBasso** [mtaheij/PoGo-UWP#12]
Some bugs and todos for orientation:
-level upgrade updates only after logon, should be checked after every action gaining XP
-XP progress not updated in main screen and player profile (prograssbars), updates after logon
-changing buddy not updated in main screen, updates after logon
-set/view buddy pokemon not set/changed as in official client: needs additional UI

**Comment by mtaheij** [comment]
The XP progress is actually updating in the main screen and on the player profile. At least for catching pokémon and searching pokéstops.
Level upgrades are sometimes 'seen' as they happen. Currently, I'm trying to figure out where else to look for them.

**Comment by DarkLegend481** [comment]
Another Bug: When catching some Pokémon, the game freezes or crashes.

**Comment by mtaheij** [comment]
'Some' Pokémon, can you be more specific? Is it always with those types or random types?
Do you have a possibility to debug the app in Visual Studio, to see which pokémons it is about?

I only get a crash sometimes when opening the nearby panel. Not yet figured out why... The debug output doesn't show anything.

**Comment by DarkLegend481** [comment]
For me, the game slows when Bulbasaur spawns, or Golbat, and sometimes Pidgeotto...

**Comment by DarkLegend481** [comment]
My PoGo doesn't work, it says "Getting GPS Signal...", and 3 seconds later: "Something went wrong and app may be unstable now. Do you want logout and try again?"

**Comment by DarkLegend481** [comment]
I tried 2 PokéHash keys with it, and it gives the same error...

**Comment by mtaheij** [comment]
I've found that Niantic has changed something on the login routines and the app can't log in at the moment. More people and different apps are having the same issue.

There is a 'SESSION_INVALIDATED' response on the first request. Have to find out a fix for this.

**Comment by DarkLegend481** [comment]
On my brother's Lumia 520, if it throws 2 items (Berries, Pokéballs, etc...), the game crashes or stop working... Sometimes, the items get buggy and the items don't throw...

**Comment by BadiBasso** [comment]
Closing this as the first three seem to be fixed and the last was only a suggestion for the future.
