### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by DarkLegend481** [mtaheij/PoGo-UWP#13]
Info:
---------------

I finally finished the first part of Pokémon in 3D, I took advantage and added their cries.
[Pokémon GO - Assets Kit #1.zip](https://github.com/mtaheij/PoGo-UWP/files/759267/Pokemon.GO.-.Assets.Kit.1.zip)

**Comment by DarkLegend481** [comment]
PNG - Nearby and Pokémon Page
GIF - Pokémon Detail and Catching
Cries - Pokémon Detail (click on that pokémon)

**Comment by DarkLegend481** [comment]
From 2nd Gen, only Cleffa, Togepi, Togetic, Espeon, Umbreon, Tyrogue, Igglybuff, Pichu, Smoochum, Elekid and Magby have GIFs, Cries and PNGs.

**Comment by mtaheij** [comment]
The Zip file can't be extracted on my machine. I would love to take a look on what you did.

**Comment by DarkLegend481** [comment]
[Pokémon GO - Assets Pack.docx](https://github.com/mtaheij/PoGo-UWP/files/759389/Pokemon.GO.-.Assets.Pack.docx)

Rename it from .docx to .zip

**Comment by DarkLegend481** [comment]
If don't work, I'll put it on mediafire...

**Comment by DarkLegend481** [comment]
Here are the medals from 0.51.2 Version

![medals update 1](https://cloud.githubusercontent.com/assets/22161127/22735706/10f46924-ede2-11e6-925c-35677ff6450f.png)

And here the loading screen

![pokemon-go-loading-screen](https://cloud.githubusercontent.com/assets/22161127/22735778/65e59f8e-ede2-11e6-89a9-57fd5f93b90a.png)

**Comment by DarkLegend481** [comment]
PoGo has 2 stages of charging right? So we just need to edit the loading screen for these 2 stages ...

**Comment by DarkLegend481** [comment]
![z4ub6be](https://cloud.githubusercontent.com/assets/22161127/22754859/17af2e84-ee28-11e6-9edc-cdccd9d1b62a.png)
![pokemon-go-canada-2-576x1024](https://cloud.githubusercontent.com/assets/22161127/22754856/17aa51ca-ee28-11e6-9def-dc7b6b1af7ed.jpg)
![10km_egg](https://cloud.githubusercontent.com/assets/22161127/22754858/17ad9312-ee28-11e6-9a24-1244d81fddb1.png)
![5km_egg](https://cloud.githubusercontent.com/assets/22161127/22754857/17ad344e-ee28-11e6-9897-3876de7cc0f4.png)

**Comment by DarkLegend481** [comment]
Type Icons:
![bug](https://cloud.githubusercontent.com/assets/22161127/22756219/92df3f2c-ee2d-11e6-9110-388185af7c8b.png)
![dark](https://cloud.githubusercontent.com/assets/22161127/22756212/92bcb3f8-ee2d-11e6-9921-2ccd22ff46a0.png)
![dragon](https://cloud.githubusercontent.com/assets/22161127/22756217/92cad442-ee2d-11e6-9f4a-cfa406c34539.png)
![electric](https://cloud.githubusercontent.com/assets/22161127/22756213/92be68c4-ee2d-11e6-9c3d-6ca74073ffe2.png)
![fairy](https://cloud.githubusercontent.com/assets/22161127/22756216/92c7ffce-ee2d-11e6-8fdc-a48c1dde80d2.png)
![fighting](https://cloud.githubusercontent.com/assets/22161127/22756215/92c6668c-ee2d-11e6-9040-744e548254cd.png)
![fire](https://cloud.githubusercontent.com/assets/22161127/22756214/92c4a2d4-ee2d-11e6-990b-3b3c9fd26120.png)
![flying](https://cloud.githubusercontent.com/assets/22161127/22756211/92ba7890-ee2d-11e6-8fe6-28b6e7dbcd5a.png)
![ghost](https://cloud.githubusercontent.com/assets/22161127/22756218/92d3cbec-ee2d-11e6-9d13-34b8ca42f225.png)
![grass](https://cloud.githubusercontent.com/assets/22161127/22756209/92b9582a-ee2d-11e6-8184-9f22c35ac465.png)
![ground](https://cloud.githubusercontent.com/assets/22161127/22756229/93674a70-ee2d-11e6-822c-cfe6e7c653d3.png)
![ice](https://cloud.githubusercontent.com/assets/22161127/22756220/92e8f3aa-ee2d-11e6-8b1d-21f5257da8ba.png)
![normal](https://cloud.githubusercontent.com/assets/22161127/22756221/92ec3542-ee2d-11e6-83dc-891e72006b88.png)
![poison](https://cloud.githubusercontent.com/assets/22161127/22756210/92b946d2-ee2d-11e6-8387-b2bd73cae23a.png)
![psychic](https://cloud.githubusercontent.com/assets/22161127/22756223/92ed6ebc-ee2d-11e6-8e62-88082792d711.png)
![rock](https://cloud.githubusercontent.com/assets/22161127/22756226/92ffdf98-ee2d-11e6-83c4-2afdd817f559.png)
![steel](https://cloud.githubusercontent.com/assets/22161127/22756225/92fd5afc-ee2d-11e6-9b23-8ccd7aff5be0.png)
![water](https://cloud.githubusercontent.com/assets/22161127/22756224/92f4d2d8-ee2d-11e6-8a30-4684b41aa76a.png)

**Comment by mtaheij** [comment]
Thank you, a couple of thoughts:
- the animated gifs do not have a transparent background, I think that's not possible in .gif format, is it? I think they cannot be used without a transparent background. Once the app has more functionality, I plan to take a look at integrating Unity for 3d models.
- the PNG's are not complete for gen2, there are already PNG's in the app, also in a higher resolution
- Cries, that's something we can do in an update. 
- There are a lot more medals extracted from the 0.51.2 version, we can certainly use them. Do they have names? On Github, they get GUID names. This is also for the two new eggs and the type icons. Can you tell me where these are used? I do not have an Android or iPhone to check.
- A new loading screen is ready in my next release, I don't think we will use the festival backgrounds, as they appear only in new versions.
- There is already an asset for the 'group photo' available, a textbox can be put on top to show additional information when needed.

Anyway: thank you for your search after assets. Some of them can certainly be used.

**Comment by DarkLegend481** [comment]
Ex: Hiker uses the Rock Medal
        Swimmer uses the Water Medal, etc...

**Comment by DarkLegend481** [comment]
New look for medals:
![images](https://cloud.githubusercontent.com/assets/22161127/22758105/5fabced4-ee34-11e6-8204-bf17ed82d109.jpg)
The orange egg is for 5km egg and purple for 10km egg

**Comment by DarkLegend481** [comment]
It's the same medals but with new icons

**Comment by DarkLegend481** [comment]
Type icons replace the names of the types in the Pokémon Detail Page

**Comment by mtaheij** [comment]
Ahh, ok. I don't have the original app, so I have to see how it looks by watching YouTube video's :-/
With the risk that I'm looking at old video's that have screens that were updated later.

**Comment by mtaheij** [comment]
But do the images have real names? Now, I can't determine them as they are uploaded and given a GUID name.

**Comment by DarkLegend481** [comment]
I downloaded them from random sites, I don't remember their names...

**Comment by DarkLegend481** [comment]
But, you can't give a name like:
fairy_type_icn.png
And the medals:
medal_pikachufan_silver.png
??

**Comment by DarkLegend481** [comment]
Eggs:
Egg_5km.png
?

**Comment by DarkLegend481** [comment]
Medal names:
![wp_ss_20170208_0003](https://cloud.githubusercontent.com/assets/22161127/22759367/54936714-ee39-11e6-80d3-0d25e468773c.png)
![wp_ss_20170208_0004](https://cloud.githubusercontent.com/assets/22161127/22759368/5497b99a-ee39-11e6-9563-61049ab1184f.png)
![wp_ss_20170208_0005](https://cloud.githubusercontent.com/assets/22161127/22759366/54917e36-ee39-11e6-912e-bb5c79a61440.png)

**Comment by DarkLegend481** [comment]
![festive_pikachu](https://cloud.githubusercontent.com/assets/22161127/22759655/5b81a990-ee3a-11e6-9a0a-5e8ff0d35b8e.png)

**Comment by DarkLegend481** [comment]
Oh, now medals like Swimmer increases spawn rate of that Pokémon type

**Comment by DarkLegend481** [comment]
Like:
Swimmer = +Water Pokémon
Hiker = +Rock Pokémon
Kindler = +Fire Pokémon

**Comment by BrazilianBug** [comment]
Hello, I did a Splash Screen for pogo, a "pirated" version of the Niantic logo, I did a parody with the mascot of windows insider.

It's been a while since I've done it, but if you wish I can redo or change something, I also put the IOS PokemonGo icon in POGO, but it was not all the images that Visual Studio accepted. If you wanted to let me know, I upload it .

LINK: https://www.mediafire.com/?34knjgm5jbbwk3s

Sorry for my english, I'm Brazilian, I'm using Google Translate.

**Comment by DarkLegend481** [comment]
@BrazilianBug Isso nao deveria estar na vertical? Mas, mesmo assim, ficou ótimo cara, parabéns!

**Comment by BrazilianBug** [comment]
This is the limit allowed in Splash Screen, if it gets bigger it would be very small
![iwsn7](https://cloud.githubusercontent.com/assets/21015826/22762805/552388ee-ee48-11e6-99a7-dac95e248938.png)

PT-BR Text> Este é o limite permitido na Splash Screen, se ficar maior ela estaria muito pequena

**Comment by mtaheij** [comment]
Type Icons:
![bug](https://cloud.githubusercontent.com/assets/22161127/22756219/92df3f2c-ee2d-11e6-9110-388185af7c8b.png)
![dark](https://cloud.githubusercontent.com/assets/22161127/22756212/92bcb3f8-ee2d-11e6-9921-2ccd22ff46a0.png)
![dragon](https://cloud.githubusercontent.com/assets/22161127/22756217/92cad442-ee2d-11e6-9f4a-cfa406c34539.png)
![electric](https://cloud.githubusercontent.com/assets/22161127/22756213/92be68c4-ee2d-11e6-9c3d-6ca74073ffe2.png)
![fairy](https://cloud.githubusercontent.com/assets/22161127/22756216/92c7ffce-ee2d-11e6-8fdc-a48c1dde80d2.png)
![fighting](https://cloud.githubusercontent.com/assets/22161127/22756215/92c6668c-ee2d-11e6-9040-744e548254cd.png)
![fire](https://cloud.githubusercontent.com/assets/22161127/22756214/92c4a2d4-ee2d-11e6-990b-3b3c9fd26120.png)
![flying](https://cloud.githubusercontent.com/assets/22161127/22756211/92ba7890-ee2d-11e6-8fe6-28b6e7dbcd5a.png)
![ghost](https://cloud.githubusercontent.com/assets/22161127/22756218/92d3cbec-ee2d-11e6-9d13-34b8ca42f225.png)
![grass](https://cloud.githubusercontent.com/assets/22161127/22756209/92b9582a-ee2d-11e6-8184-9f22c35ac465.png)
![ground](https://cloud.githubusercontent.com/assets/22161127/22756229/93674a70-ee2d-11e6-822c-cfe6e7c653d3.png)
![ice](https://cloud.githubusercontent.com/assets/22161127/22756220/92e8f3aa-ee2d-11e6-8b1d-21f5257da8ba.png)
![normal](https://cloud.githubusercontent.com/assets/22161127/22756221/92ec3542-ee2d-11e6-83dc-891e72006b88.png)
![poison](https://cloud.githubusercontent.com/assets/22161127/22756210/92b946d2-ee2d-11e6-8387-b2bd73cae23a.png)
![psychic](https://cloud.githubusercontent.com/assets/22161127/22756223/92ed6ebc-ee2d-11e6-8e62-88082792d711.png)
![rock](https://cloud.githubusercontent.com/assets/22161127/22756226/92ffdf98-ee2d-11e6-83c4-2afdd817f559.png)
![steel](https://cloud.githubusercontent.com/assets/22161127/22756225/92fd5afc-ee2d-11e6-9b23-8ccd7aff5be0.png)
![water](https://cloud.githubusercontent.com/assets/22161127/22756224/92f4d2d8-ee2d-11e6-8a30-4684b41aa76a.png)

**Comment by Jao78** [comment]
@DarkLegend481
The PokeHash Expired
When get other

**Comment by DarkLegend481** [comment]
@Jao78 Estou procurando outra chave PokéHash... Quando achar, mando no WhatsApp...

**Comment by DarkLegend481** [comment]
This icons are the type icons, not the medals...

**Comment by Malavos** [comment]
@DarkLegend481  eu vou trabalhar também na minha interface, mas vai ser um pouco diferente. Tô planejando algo um pouco mais autenticamente digital.

**Comment by DarkLegend481** [comment]
@Malavos alguma prévia??

**Comment by Malavos** [comment]
@DarkLegend481  quando meu pc novo chegar e meu projeto atual acabar :timer_clock:

**Comment by DarkLegend481** [comment]
2nd Generation Trailer Image #1:
![wp_ss_20170215_0004](https://cloud.githubusercontent.com/assets/22161127/22983287/c8f5ab68-f388-11e6-9fda-0cf22083f56e.png)

**Comment by Malavos** [comment]
:clap: :clap: :clap:

**Comment by DarkLegend481** [comment]
O ruim é que teremos que atualizar a API e todo o resto quando a update sair...

**Comment by Malavos** [comment]
@DarkLegend481  já entrei pra seita já.

**Comment by DarkLegend481** [comment]
@Malavos Kkkkkkkk

**Comment by DarkLegend481** [comment]
Como será que funciona a troca de berries e a troca de pokéballs durante a gameplay??

**Comment by BadiBasso** [comment]
http://serebii.net/pokemongo/medals.shtml

**Comment by DarkLegend481** [comment]
I got the description of Metal Coat, Sun Stone, Nanab Berry and Pinap Berry. Dragon Scale, Up-grade and King's Rock it's missing.

**Comment by DarkLegend481** [comment]
![nanab-berry-pokemon-go](https://cloud.githubusercontent.com/assets/22161127/23098632/4bface98-f632-11e6-891a-24d21155abf7.png)
![pinap-berry-pokemon-go](https://cloud.githubusercontent.com/assets/22161127/23098634/4bfdc666-f632-11e6-8b26-69e7480012c0.png)
[Pokémon GO Items Description.docx](https://github.com/mtaheij/PoGo-UWP/files/785497/Pokemon.GO.Items.Description.docx)
![pokemon-go-dragon_scale-150x150](https://cloud.githubusercontent.com/assets/22161127/23098633/4bfb800e-f632-11e6-8d46-8522db94fcf2.png)
![pokemon-go-kings-rock-150x150](https://cloud.githubusercontent.com/assets/22161127/23098638/59cda8c4-f632-11e6-86b5-9b7b1d4f0878.png)
![pokemon-go-metal-coat-150x150](https://cloud.githubusercontent.com/assets/22161127/23098639/59d0b244-f632-11e6-8f25-471695337cd6.png)
![pokemon-go-sun-stone-150x150](https://cloud.githubusercontent.com/assets/22161127/23098640/59d11fea-f632-11e6-9d91-3ae4a25f951c.png)
![pokemon-go-up-grade-150x150](https://cloud.githubusercontent.com/assets/22161127/23098637/59cd2d22-f632-11e6-8de0-8f66f86196a5.png)

**Comment by BadiBasso** [comment]
Better Gen2 assets here: http://pokemongo.wikia.com/wiki/Pok%C3%A9dex
Seem to be extracted from official client.
As of now all Gen2 icons are not yet there, but I trust they will be available in the near future

**Comment by DarkLegend481** [comment]
My brother uses a Lumia 520, he can not play PoGo. The game just opens and drops SplashScreen and then closes. Any tips?

**Comment by mtaheij** [comment]
After updating to 1.2.8?
You can try removing the app completely and reinstall, or remove, reboot, install.
My son's 650 had similar problems, but after a few attempts, it's working now.

**Comment by Thedeveloperfairy** [comment]
Hey will we be able to have our avatar from the official game. In this version? Instead of the girl and boy avatar that is their currently.

**Comment by mtaheij** [comment]
For the avatar, we will need Unity3d in our game. This can be done, but needs some research.

**Comment by DarkLegend481** [comment]
But, to use Unity... We don't have to rewrite the game on Unity code?

**Comment by mtaheij** [comment]
I is possible to load the Unity part 'on top of' the UWP pages. But I haven't found time yet to look into this. First thing was to get as many functions in the app as possible.

Training and fighting is one of the first things where Unity would really be necessary (and if that works, we can rewrite the capture page as well).

**Comment by DarkLegend481** [comment]
I renembered a thing now... Log out button are placed behind settings button
