### ISSUE TITLE
This error message every 5 seconds!!

### ISSUE THREAD

**Issue by DenisRraku** [mtaheij/PoGo-UWP#130]
Something went wrong and the app may be unstable sth like this.  Fix thiss!!

**Comment by BadiBasso** [comment]
Thank you for your detailed submission of an issue. The devs may contact you as soon as they have some insight concerning this.

**Comment by ntaheij** [comment]
Explain more please
Did you you try to uninstall and install the app?

**Comment by DenisRraku** [comment]
App is working fine now. I'm gonna close the issue
