### ISSUE TITLE
MAP NOT LOADING!!

### ISSUE THREAD

**Issue by DenisRraku** [mtaheij/PoGo-UWP#131]
Lumia 640
Version 1.3.5

**Comment by DavidWForeman** [comment]
I have noted on a 950XL that the map loads but it is needs to be moved then press the my location icon.  Sometimes it is zoomed out to beyond the local region.  I was told earlier that this is a problem with Windows Developer builds.  Whilst I am prepared to believe this I wonder why the maps app always works properly - I believe it is using the same map engine via API?

**Comment by ntaheij** [comment]
Did you update your windows? There were issues about it
