### ISSUE TITLE
after i open the app ...

### ISSUE THREAD

**Issue by Swarajsm** [mtaheij/PoGo-UWP#138]
Device info
------------------
- Phone type : lumia 535
- App version: (e.g. 1.0.25)

Steps to reproduce
Open the app 
Enter credentials 
And poof

Actual behavior
It shows an error

Expected behavior
App should open

Other information
Whenever i try to open it says 
Something went wrong and app may be instable now. Do you want to logout and try again

**Comment by lutra333** [comment]
I have the same problem at my Lumia 950DS with 1.3.5 version of the app. Deinstalling app, reboot the phone and installing it again does not help

**Comment by Swarajsm** [comment]
It started happening after i got level 30

**Comment by mtaheij** [comment]
Should now work again, with version 1.3.6
You can close the issue when it does.
