### ISSUE TITLE
Basic GYM Suport

### ISSUE THREAD

**Issue by BrazilianBug** [mtaheij/PoGo-UWP#14]
English Text
Hello, When POGO-UWP was still alive there was a PR to add a basic system of GYM, we could see who was there, and even possibly put a pokemon. I would like to know the chances of implementing these features in your project.

Link> https://github.com/ST-Apps/PoGo-UWP/pull/1715
Link> https://github.com/ST-Apps/PoGo-UWP/pull/1743

Text in Portuguese
Olá, Quando POGO-UWP ainda era vivo havia uma PR para adicionar um sistema basico de GYM, poderiamos ver quem estava lá, E até possivelmente colocar um pokemon. Gostaria de saber quais as chances de implementar estes recursos no seu projeto.

**Comment by DarkLegend481** [comment]
@mtaheij já disse que iria adicionar em uma update... Mas nao sei se haverá batalhas...

**Comment by DarkLegend481** [comment]
Se você olhar a última commit, vai ver que as mudanças envolvendo Gyms já começaram...

**Comment by BrazilianBug** [comment]
As batalhas eu sei que não irão ocorrer, já que nestes PR já diziam que era apenas para ver o GYM, no máximo colocar um pokemon caso estivesse disponível, o outro PR é as animações para caso alguém crie o sistema de batalhas, Este projeto esta bem mais promissor do que o Pogo do ST-APPS.

**Comment by mtaheij** [comment]
In the latest commit there is basic support for gyms, the databinding is not correct, but I wanted to show you some extra changes. This weekend, the gym support will be further extended (no fighting or training).

**Comment by DarkLegend481** [comment]
No battles? Phew... But, in (https://github.com/ST-Apps/PoGo-UWP/pull/1743) We have the codes for battling and training... Not completed (I seems), but useful...

**Comment by mtaheij** [comment]
Actually, I copied in the changes from https://github.com/ST-Apps/PoGo-UWP/pull/1715 for the Gym UI.
The animation that is shown in https://github.com/ST-Apps/PoGo-UWP/pull/1743 doesn't have actual gameplay, it's an animation of how it could look. 

As a matter of fact, it's not clear what requests we need to sent during a battle.
We have to be careful implementing trainings and battles, as they (Niantic) might be able to detect we are not using the official app if we send requests in the wrong order, incomplete requests or something like that.
That's why the basic UI, showing the current Gym contents is not that difficult and even deploying a Pokémon to a gym is easy.

**Comment by DarkLegend481** [comment]
We can use this?:
![wp_ss_20170209_0001](https://cloud.githubusercontent.com/assets/22161127/22787031/00975bbe-eec2-11e6-8c6b-8ecbb9602b6a.png)
Provided by @Malavos

**Comment by mtaheij** [comment]
I'm not sure how this is related to Gym support, but why should you want to use this?
The current API implementation is a 'proved concept' using a device profile that looks legit to Niantic when sent in a request.

**Comment by Malavos** [comment]
@mtaheij  are you sure about that? If so, how did they track way back, the first ban batch?The ID looks like out of standart from the Device ID from apple and droid.

I started a discussion about that with another user, but I still did not have the time to make a code review over that.

**Comment by BadiBasso** [comment]
https://github.com/ST-Apps/PoGo-UWP/issues/575

**Comment by Malavos** [comment]
@BadiBasso  yeah, not real a deviceID there.

**Comment by BadiBasso** [comment]
@Malavos PR coming soon to correct this issue, I hope?

**Comment by Malavos** [comment]
I can't work on anything for this project right now. I hope maybe by the end of this month. I wanted to also port it to something else. We'll see....

**Comment by mtaheij** [comment]
I had some trouble implementing the 'choose team' dialog. 
This is now almost done, in the next release you will be able to:
- see gyms on the map
- when opening a gym when you're not yet level 5, you will be asked by the professor to return when you've reached level 5.
- choose a team
- see the details of a Gym, including al deployed pokémons (memberships)
- deploy a pokémon to a gym
As I said, some setbacks, but it will be available this week.

**Comment by Malavos** [comment]
@mtaheij  you're the best.

I hope I can help by the end of this month. Keep going!

**Comment by BadiBasso** [comment]
@mtaheij Have you checked this: https://github.com/Necrobot-Private/NecroBot/blob/v1.0.0.101/PoGo.NecroBot.Logic/Tasks/UseGymBattleTask.cs
Seems to have most, of not all, necessary methods for training/battling

**Comment by mtaheij** [comment]
Can anyone try with the latest source version to deploy a pokemon to a gym? I always get the message 'Gym is full'.

**Comment by andremvm** [comment]
Sadly right now all (or the ones I know of) in my city are from a different team and already level 10 gyms, so I don't think I will be able to try it any time soon...

**Comment by mtaheij** [comment]
I have successfully deployed a Pokémon to a level 2 gym this afternoon.
