### ISSUE TITLE
!Very unsafe!

### ISSUE THREAD

**Issue by Darknoz** [mtaheij/PoGo-UWP#155]
Hi,

App is very unsafe! I banned on my old account, created a new one. Ban again in 3 days. I was lvl 15 on the new account.

Pls make safer, unplayable.

**Comment by mtaheij** [comment]
Any suggestions on how to make it safer?

**Comment by Darknoz** [comment]
I dont know. I will test again. Try play with limitations. Example: Only 10 pokemon / day, throwing pokeballs to miss, etc. I think 3 problems with app. 

1. Pokeball throwing mechanism. Try develop a random miss chance for it, because currently 100% hit the pokemon with same gesture.

2. Pokemon catching mechanism. If pop up a nearby pokemon on a map can catch always, its not depends on distance. Implement a range check (few yards) if possible. So now I can catch a pokemon with 2-3 streets to my current position. 

3. Eggs are often start with -0.2km. If it sent to server maybe bannable idk.

+1: Implement a limiter (optional for use). And make rules: 10 pokemon catch / day, 11 km / day. 

I think with PoGO can collect Pokemons faster than official version, limit this.

I never used official version, I love W10 platform and your work. I will start again and again with new account if I banned. Thanks your work :)

**Comment by WodsonKun** [comment]
Anyone knows PoGo's URI scheme?

**Comment by mtaheij** [comment]
How do you mean URI scheme? There is only one API endpoint, it's all in the code.
