### ISSUE TITLE
Tutorial Mode

### ISSUE THREAD

**Issue by DarkLegend481** [mtaheij/PoGo-UWP#18]
Are you planning to put tutorial mode in PoGo?

**Comment by DarkLegend481** [comment]
Because then we will not need an Android or iOS device to pick up our initial Pokémon

**Comment by andremvm** [comment]
Actually I have never used an Android or iOS for this account, and the only thing that happened is that I wasn't able to catch one of the initial pokémon. Still, so far the account has not been banned!

**Comment by mtaheij** [comment]
Tutorial mode is next on my list to do. I will let your account look more legit.

**Comment by BadiBasso** [comment]
My current account has neither gone through tutorial. All good so far...

**Comment by mtaheij** [comment]
To be able to deploy a Pokémon into Gyms, there are some prerequisites. 

Some of the errors that can be returned are:
- FortDeployPokemonResponse.Types.Result.ErrorPlayerBelowMinimumLevel
- FortDeployPokemonResponse.Types.Result.ErrorPlayerHasNoTeam
- FortDeployPokemonResponse.Types.Result.ErrorPlayerHasNoNickname

The first two are taken care of now as you get a dialog when trying to enter a gym.
Only one left is to set a Nickname for the player, which is part of the Beginner tutorial part.

Besides that, it's better to be able to play Pokemon Go without having to use an Android or iPhone device first.

**Comment by DarkLegend481** [comment]
For anyone with are having issues with login on PTC account, Niantic says they are trying to fix that.

**Comment by DarkLegend481** [comment]
@mtaheij My brother can't run PoGo, it only shows SplashScreen and closes...

**Comment by DarkLegend481** [comment]
Niantic already fixed PTC Login

**Comment by mtaheij** [comment]
Tutorial mode is available from version 1.2.8 upwards.

**Comment by andremvm** [comment]
Thanks for adding this feature. Actually it was working also with the 1.2.7 version that was online for an hour or so (it just took some patience, and involved changing to niantic maps, logging off and on again,...). But now all the new pokemon are very tiny on the map, they can barely be seen! Any reason why the size changed?

**Comment by mtaheij** [comment]
I know it was working in the 1.2.7 version, but one of the phones just didn't work on that .appxbundle
So I rebuilt it to 1.2.8 and still no luck. After rebooting the phone twices, removing the app completely and turning around in circles for five minutes and doing the hulahoop, it suddenly worked.

the v2 pokémon are from a different source that had the images scaled inside the .png files, which is not correct for our purpose. I will try to get better v2 Pokémon images soon.
