### ISSUE TITLE
New Live Tiles for POGO

### ISSUE THREAD

**Issue by BrazilianBug** [mtaheij/PoGo-UWP#20]
![square310x310logo scale-150](https://cloud.githubusercontent.com/assets/21015826/23230588/5b58a74a-f923-11e6-84c0-3324e0d8d1b8.png)
![wide310x150logo scale-125](https://cloud.githubusercontent.com/assets/21015826/23230589/5b58bb7c-f923-11e6-9485-aa76d2919303.png)

I do not know how to create a PR, so this is an Inssue of Complaint / Request.

First of all, Excuse me for my English.

Hello, I would like to suggest new Live Titles for POGO, it's basically the Live Title of PokemonGO Official, but without the bordered edges.
I also adapted the Live Titles "Wide", made a simple assembly to be similar to the others.

Note: Some proportions of Live Title have rejected Visual Studio (I do not know why) so I'll be leaving the original images.

Thanks for your attention, .rar file at the link below.

LINK>  **# https://www.mediafire.com/?rgz9u3pigc4h38t**

(Below, Text in PT, Please answer in English for the understanding of all.)

(Abaixo. Texto em PT-BR, Por favor, Responder em Ingles para o entendimento de todos.)

Não sei criar uma PR, portanto esta é uma Inssue de Sujestão/Solicitação.

Primeiramente, Desculpem-me pelo meu Ingles.

Olá, Gostaria de sugerir novas Live Titles para o POGO, é basicamente a Live Title do PokemonGO Official, porem sem as bordas aredondadas.
Também adaptei as Live Titles "Wide", fiz uma montagem simples para ficar semelhante as outras.

Nota: Algumas proporções de Live Title o Visual Studio recusou (não sei por qual motivo) sendo assim estarei deixando as imagens originais.

Obrigado pela atenção, Arquivo .rar no link abaixo

**Comment by mtaheij** [comment]
Thanks, your tiles are added in the code. Some items still missing though, like some of the scale-400 png's.
Can you make them too? Otherwise, I can scale them using the smaller ones, but they will be blurry because of that.

**Comment by BrazilianBug** [comment]
I tried, but this problem occurs to me: "The current image exceeds the maximum image file size of 204,800 bytes. The current image file size (310 x 150) is 239,366 bytes."

![pront](https://cloud.githubusercontent.com/assets/21015826/23533638/c2607804-ff91-11e6-8c00-89aa064dda74.png)

(PT-BR Text)
Eu tentei, mas me ocorre este problema: "A imagem atual excede o tamanho máximo de arquivo de imagem de 204.800 bytes. O tamanho do arquivo de imagem atual (Logotipo Largo de 310 x 150 (escala 400)) é 239.366 bytes."

**Comment by mtaheij** [comment]
What size is the original image you are working from? If you have a high resolution version in .jpg or .png format, I can scale it down to the correct format using some other application.

**Comment by BrazilianBug** [comment]
These are the images I'm using

https://www.mediafire.com/?5ib3b2cd3j9tadh

**Comment by mtaheij** [comment]
I have converted all of the assets in the correct sizes now and these will be in the next update.
