### ISSUE TITLE
How do i get that PokeHash key? wtf

### ISSUE THREAD

**Issue by DenisRraku** [mtaheij/PoGo-UWP#22]

**Comment by mtaheij** [comment]
There is a link at the bottom of the screen where you have to enter it. Also, at the start page, there is an explanation of how to get one.
But for your convenience: https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer
A 150 RPM key is more than sufficient, and you can share it with others if you like. (can be used for about 4 to 5 accounts at the same time).
This is a paid service, not owned by me, so don't blame me for it.
Unfortunately, there is no free API at the moment.

**Comment by degzm** [comment]
Paid to play a free game?
Dafuq, fuck hash server people

**Comment by mtaheij** [comment]
Correction: Fuck Niantic for not publishing an app for Windows.

**Comment by degzm** [comment]
Oh yes, fuck Niantic, if you know Monster Buster app, you know the virtual reality is possible in windows 10 mobile, and not only vr...
