### ISSUE TITLE
Captcha issue

### ISSUE THREAD

**Issue by Dragoncat4** [mtaheij/PoGo-UWP#24]
Device info
------------------
- App version: newest

Steps to reproduce
----------------
Just walk.

Actual behavior
-----------------
The number of captchas is crazy. I could basically finish one and 5 seconds later get another one. Is it known why such frequency of captchas occurs? Is it due to a wide range of pokemon detection? Or lacking of "I'm a passager" button (although should not apply, I was just walking)?

Expected behavior
---------------
Barely any captchas should occur.

Other information
---------------

**Comment by andremvm** [comment]
I guess that will not depend on the app itself, but on the API Hashing service and on the amount of requests it is making to the server... For me it is completely random, sometimes I spend 1 full day just doing 1-2 captchas, other times it is like you say, one after another!

**Comment by BadiBasso** [comment]
Have noticed that whenever new version is enforced the captcha rate increases.for a time and then settles.

**Comment by ntaheij** [comment]
When you walk an straight line, it will give more capthas, also if you walk from pokestop to pokestop to pokestop it also will give you more capthas, when just walk around and not straight and from pokestop to pokestop you will get less capthas

**Comment by andremvm** [comment]
Sometimes, even if I do the captcha correctly, somehow for long periods of time (usually like 1 hour or more) I will not be able to see any pokestop or pokemon, and the distance is not being updated... Anyone having this issue as well?

**Comment by ntaheij** [comment]
When you have that, you can be soft banned, by niantic if they still thing you're cheating

**Comment by andremvm** [comment]
Oh, ok then... I hope that won't bring to a permanent ban of my account which has been safe so far! :)

**Comment by mtaheij** [comment]
Anyone had captchas using the latest version? I haven't had one (but again: I'm not a big time user now)

**Comment by andremvm** [comment]
Walked more than 10 km with the app running yesterday and not a single captcha!

**Comment by mtaheij** [comment]
Very nice! Closing this issue :-)
