### ISSUE TITLE
Live Tiles don't changing

### ISSUE THREAD

**Issue by DarkLegend481** [mtaheij/PoGo-UWP#26]
Device info
------------------
- Phone type: NOKIA Lumia 635
- App version: 1.2.9

Steps to reproduce
----------------
Pokéball button > Settings > Select a live tile

Actual behavior
-----------------
The only live tiles are working is Normal and Peek.

Expected behavior
---------------
All live tiles working

Other information
---------------
If I choose Peek live tile, I have to select Normal live tile a bunch of times to return to normal.

**Comment by ntaheij** [comment]
This is a well known issue. This will be fixed in the next update

**Comment by DarkLegend481** [comment]
OK!

**Comment by ntaheij** [comment]
Just as a reminder, keeping this one open.

**Comment by DarkLegend481** [comment]
Oh, OK! Sorry :)

**Comment by mtaheij** [comment]
Don the best I can. But the new LiveTile Notifications system is a strange thing. You should be able to choose a live tile now in the settings, and it will update accordingly, but the 'peek-style' scrolling images keep appearing and sometimes, you will get images from a set you have chosen before. Not important enough in my opinion to stare at the code for another couple of hours. As mentioned: the next release will have this corrected.
