### ISSUE TITLE
Very tiny 2nd generation pokemon

### ISSUE THREAD

**Issue by Dragoncat4** [mtaheij/PoGo-UWP#27]
Device info
------------------
- Phone type: Lumia 659 DS
- App version: 1.2.9

Steps to reproduce
----------------
N/A

Actual behavior
-----------------
Second generation images both on the map and in Pokemon selection window are very small (something like 1/8 of first generation monsters). 

Expected behavior
---------------
Dimensions of the images of 2nd Pokemon generation should be similar to those of 1st generation.

Other information
---------------
I can provide a screenshot if necessary.

**Comment by ntaheij** [comment]
This is a known issue, we are trying to get lager image files. For now we have the smaller ones.

**Comment by mtaheij** [comment]
We have found some better images. They are not completely high resolution, but the pokémon show bigger on the map, in nearby, in catching and in the inventory.

**Comment by andremvm** [comment]
You didn't include the new images in the version 1.29, right?

**Comment by mtaheij** [comment]
No, they are in the code already, but not yet in the compiled/released version.
So if you know how to build the app from source files and deploy it to your device, you will get the new images instantly. Otherwise, you'll have to wait for version 1.2.10 (hopefully tonight)

**Comment by andremvm** [comment]
I don't exactly know how to do it, but anyway it's not so urgent since we cannot login yet! :P
