### ISSUE TITLE
QUESTION> Disclosure of your project

### ISSUE THREAD

**Issue by BrazilianBug** [mtaheij/PoGo-UWP#28]
Why not advertise your POGO on GitHub of the original POGO? There are still a lot of active people there, so it would be a great help for them to contribute to your project.

**Comment by mtaheij** [comment]
I sometimes post a message on the original POGO-UWP by ST-Apps that there is a new version available.
But where do you see 'a lot of active people' there? Please invite everyone to join the party here!

**Comment by BrazilianBug** [comment]
https://www.windowsclub.com.br/pokemon-go-uwp-volta-com-nova-versao-ao-windows-10/

**Comment by ntaheij** [comment]
Not needed anymore, I think, else, reopen it.
