### ISSUE TITLE
Idea!

### ISSUE THREAD

**Issue by DarkLegend481** [mtaheij/PoGo-UWP#3]
Intro
---------------
After @ ST-Apps leave the original PoGo repository, I think now we should give one make-oven in PoGo ...

Proposes
---------------
3D-like Pokémon and some assets
Buddy System
2nd Gen (Eggs)
Gym's (Not activated)
Multi-transfer system
Revamped game pages
A new icon
A new load screen
Journal

I think @ST-Apps will not care about these changes... If we give credit... But, if we want play Pokémon GO like the iOS/Android users... We need make these changes...

**Comment by DarkLegend481** [comment]
I'm working on some of these changes:

3D-like Pokémon = 25%
New loading screen = 100% (The same as Pokémon GO)
New icon = We can use the same as Pokémon GO!
New game pages = Starting...

**Comment by mtaheij** [comment]
- I the current release, you can already choose a Buddy Pokemon, thanks to @Badibasso (who seems to have left as well).
- 2nd Gen pokemon assets are in this version as well, don't know about eggs yet. Think it will work.

Why do we need new game pages? Better get functionality in first, or do you disagree here?
I'm currently working on the sounds, have added a few to make the gameplay somewhat more like the original.
After that, Multi-transfer and Journal are on my list.

**Comment by DarkLegend481** [comment]
OK

**Comment by DarkLegend481** [comment]
But, the loading screen and the 3D-like assets?? Are you planning something?

**Comment by DarkLegend481** [comment]
Hey, this key will work on PoGo?
Key: 7C8E1R3V0U4L9J9W0A7B

**Comment by DarkLegend481** [comment]
Sorry, I forgot I had the key could not be disclosed...

**Comment by mtaheij** [comment]
It looks like a valid hashing key.
Just to make sure: Log in to the buddyauth.com website and take a look in the 'keys' page.
If your key is mentioned as a 'Pokehash' type key, you are good to go.
(For your protection, I've removed it from your post)

**Comment by DarkLegend481** [comment]
OK

**Comment by DarkLegend481** [comment]
I don't bought it, I found it on a bot...

**Comment by DarkLegend481** [comment]
But, on their site, says:
-We bought a key to free use (or something like that...)

**Comment by mtaheij** [comment]
Ah, ok. This will probably not work, as there is only one session allowed. If the hashing server receives requests from different locations / ip addresses at the same time, it will give a fail response (I think).
But you can always try...

**Comment by DarkLegend481** [comment]
Are you??

**Comment by DarkLegend481** [comment]
Only commenting... IT WORKS!! IT WORKS!!

**Comment by BadiBasso** [comment]
Might not be a bad idea if someone focuses on UI and some other works on the backend. We all have our strengths and I think we get much more done if we separate tasks and agree upon them.

**Comment by BadiBasso** [comment]
Concerning 2gen eggs: Hatched a Smoochum in one test acc before the acc was banned.

**Comment by DarkLegend481** [comment]
I would very much like to work on PoGo UI!

**Comment by Thedeveloperfairy** [comment]
Can I help in any way possible?

**Comment by mtaheij** [comment]
Sure, any help is welcome. Is there any area that you are interested in that you would like to pick up?

**Comment by Thedeveloperfairy** [comment]
well I currently studying Computer Programming at university but I would need to learn the language that you are using as I'm currently only in my first year of university. also im currently learning Java from my university. so if you could help me learn the syntax that would be great. that if you don't mind.

**Comment by mtaheij** [comment]
We can never learn you as much as the existing resources that are out there on the internet.
Try dev.windows.com and look for learning resources there or search for any other learning initiative.
Besides that, we can better focus on getting more features in the app than trying to learn you to program C#.

**Comment by arturskyman** [comment]
Hi, it is great that update works automatically. Would it be possible to add Gyms at least to see what is in and in case of free place in our Gym to add pokemon in?

**Comment by DarkLegend481** [comment]
Gyms already are on the game, but, not "enabled"...

**Comment by arturskyman** [comment]
OK, is there a way to enable them?

**Comment by mtaheij** [comment]
I will do that shortly. Please wait for an update.
