### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by WanderingJesusFreak** [mtaheij/PoGo-UWP#30]
At about 8 EST this evening my wife and I were both unable to log in anymore. I read some other forms and it seems to be another login change. Just looking to confirm. Thanks!

**Comment by andremvm** [comment]
It happened to me as well, so you are probably right!

**Comment by RSikkel** [comment]
The net_uri_BadHostName sounds like a networking issue...

**Comment by mtaheij** [comment]
Niantic has forced version 0.57.4 / 1.27.4 yesterday and it includes a new login URI.
The one we use in POGO-UWP doesn't exist anymore. I'm trying to figure out where the login URI has changed to.

**Comment by RSikkel** [comment]
Well, I would like to thank you nonetheless for putting in all this effort :)

**Comment by andremvm** [comment]
Yes, thanks a lot for all the development!

**Comment by andremvm** [comment]
Was anyone able to install the new pre-release " v1.2.9a"? I keep trying on my Lumia 640 DS, but everytime even though I select to install (like in all previous releases), nothing ends up being installed...

**Comment by andremvm** [comment]
No problem, thanks a lot for once again rescuing this project! :)

**Comment by BadiBasso** [comment]
Got your code installed to my phone by compiling it myself. Weird thing is that phone stalls in splash screen but in VS Phone emulator I get to the map screen with full inventory, palyer stats, pokemons and dex. No pokestops though.

**Comment by BadiBasso** [comment]
BTW... Your current release is a debug build, needs app portal to install....

**Comment by BadiBasso** [comment]
Tried with another phone. Stalls as the first one.

**Comment by mtaheij** [comment]
New version is available, please check
https://github.com/mtaheij/PoGo-UWP/releases/tag/v1.2.10-beta

**Comment by DarkLegend481** [comment]
Login still not working...
