### ISSUE TITLE
PoGo-UWP is unfortunatly detected by niantic

### ISSUE THREAD

**Issue by Dragoncat4** [mtaheij/PoGo-UWP#31]
When I logged today on my friend's phone with my account the warning black screen appeared to me (identical like in this article [Link](http://www.itechpost.com/articles/37614/20161007/pokemon-go-news-and-update-niantic-is-killing-third-party-apps-adds-new-warning-feature.htm)).
So unfortunately, despite attempts of developers, accounts are flagged.

**Comment by DarkLegend481** [comment]
Looks like we will need a better DeviceID generator...

**Comment by WanderingJesusFreak** [comment]
So... Looks like borrowing my sons phone for the near future...

**Comment by andremvm** [comment]
Could that simply be because you used another device to login your account? I cannot check yet in my account, since I still have the warning about the minimum api level by the POGO-UWP team and I do not have another platform to test it...

**Comment by Dragoncat4** [comment]
No idea, basically I just used pogo-uwp and my friend's cell for the whole time of using the account. My friend was never banned nor this network was flagged.
In case you describe I'd expect at least one post on reddit pogodev about those warnings when using multiple phones, I didn't see any but on the other hand, I wasn't really searching it.

**Comment by andremvm** [comment]
Perhaps you are right... We will see if other accounts get that message or somebody gets actually banned!

**Comment by WanderingJesusFreak** [comment]
I will confirm that both my wife and I got those messages when logging into our accounts using an Android phone. However, I am also going to test my son's account. He hasn't played since the API went private, so it will be interesting to see if his account gets the same message.

**Comment by WanderingJesusFreak** [comment]
Just wondering if the newest version is any safer. I know it will never be ban proof, but I would like to know if the newest version does anything to address the issue. Thanks!

**Comment by mtaheij** [comment]
I have not yet received any captchas since the newest version. Not been a big user today but looks promising.

**Comment by WanderingJesusFreak** [comment]
I used it for 20 min today and no captchas.

**Comment by andremvm** [comment]
I finally managed to install it again (thanks to francieisking999 instructions), but only managed to play a couple minutes. Tomorrow I should have a few hours of game, I will also say if I get the captchas or not... the good thing is that the account has not been banned yet! :)

**Comment by WanderingJesusFreak** [comment]
Just wondering, does playing in the car increase the chances of being detected since we don't get the playing while driving popup?

**Comment by andremvm** [comment]
I don't think so... I used it several times while driving in the city (30-50 km/h) and almost never got captchas, only the pokemons wouldn't spawn and the pokestops wouldn't open! Usually I got the captchas while walking...

**Comment by ntaheij** [comment]
I have my account a long time since we started with PoGo-UWP. Today, I logged in on my android tablet, and no warning, and I already have it a long time

**Comment by Dragoncat4** [comment]
The warning occurred for me after 2nd or 3rd logging on official app.

**Comment by ntaheij** [comment]
Solved. If not please reopen issue
