### ISSUE TITLE
Unable to save pokehash key

### ISSUE THREAD

**Issue by RSikkel** [mtaheij/PoGo-UWP#32]
Device info
------------------
- Phone type: Lumia 950 XL
- App version: (e.g. 1.2.10)

Steps to reproduce
----------------
Remove app
Install app from scratch
Enter pokehash key

Actual behavior
-----------------
Received "Something went wrong and app may be unstable now. Do you want to logout and try again?"

Expected behavior
---------------
Go to the login screen.

Other information
---------------
Clicking yes goes back to the alert with something went wrong. If you click no the app remains on the loading screen infinitely.

After having upgraded the app I got a different error (I had extended error info enabled). If I remember correctly it was something about a missing primary key.

**Comment by LotuxPunk** [comment]
I had the same issues when i put my pokehash key

![wp_ss_20170313_0001](https://cloud.githubusercontent.com/assets/16562647/23891180/63151b90-0895-11e7-87a4-96c5c329c459.png)

**Comment by mtaheij** [comment]
Very strange. Are you sure you completely uninstalled the app before installing the new one? (should not be necessary, but if it doesn't work, you can try that).
I have a Lumia 950XL myself and I installed it by downloading it from the website too.

**Comment by RSikkel** [comment]
Quite sure. Uninstalled the app twice, redownloaded the package twice and even tried the new reset function. Never got past the pokehash entry screen. I am running the latest insider fast build, but that shouldn't make a difference right? It was working quite well before the api change :)

**Comment by mtaheij** [comment]
I'm not on any insider build but that shouldn't be a problem indeed.
Are you able to run the app from Visual Studio? You might be able to see what's going on while debugging.
I have to look in a way to use HockeyApp or some other mechanism to see errors on user devices.
Or I can try and make an 'escape' functionality in both the PokeHash key page and the Login Page to delete user settings.

**Comment by BadiBasso** [comment]
I have the same issue still. .10 installs now fine. Hash key gets saved though as it is not asked the second time you try to open the app. But still hangs at the splash screen.
My phone is also 950XL

**Comment by LotuxPunk** [comment]
I've got a 435 and same issue ^^'

I'll try with VS

**Comment by francieisking999** [comment]
same issue on a lumia 950 XL and 1520 wont run get error Something went wrong and app may be unstable now. Do you want to logout and try again?
sometimes i get error sign out again im not even signed in fix it please

**Comment by RSikkel** [comment]
If it helps, the error occurs immediately after submitting the key, even in airplane mode.

**Comment by BadiBasso** [comment]
Agree that insider build is not an issue here. I am at slow ring now (was in fast ring before but had serious problems with some other apps) Never had problems with PoGo.
Same occurs in Lumia 435 running AU which had no problems before

**Comment by RSikkel** [comment]
![image](https://cloud.githubusercontent.com/assets/22431510/23921179/eefe497a-08fd-11e7-8589-38445ebdfccc.png)
Probably not helpful, but can't get past this so far

**Comment by francieisking999** [comment]
i put in the pokehesh key then closed the app reopened it and it said something went wrong do you want top log out if i hit yes it keeps saying the error if i hit now it sits on the loading screen with the spinning dots

**Comment by porscheguy** [comment]
Just to add to the list, same issue here,  950 XL build 15055..  Could this be caused by a missing dependency?  

Thanks for all the hard work

**Comment by mtaheij** [comment]
Don't know if any dependencies are missing. They should be in the .appxbundle as far as I know.
I think it has something to do with a remainder of the authentication key that is still on the phone. The schema of the authkey has changed, so a way to remove old auth keys might resolve the problem. I Will look at that tomorrow

BTW, the hashing servers are down at the moment. See https://status.buddyauth.com/ for the status.

**Comment by porscheguy** [comment]
Thanks for the information.
 
 
 
Paul McDougal
 Red Rock Business Solutions  
 801-918-9698
 paul@tosutah.com
 www.pointofsaleutah.com
 
 
--------- Original Message --------- Subject: Re: [mtaheij/PoGo-UWP] Unable to save pokehash key (#32)

**Comment by Kamiako** [comment]
Using 950 here, let the app automatically update got the login screen then the "Something went wrong and app may be unstable now. Do you want to logout and try again?" message. Restarting app and this time got the message at the Gyarados splash screen. Hitting Yes does nothing, hitting No causes load animation forever. Manually downloaded and reinstalled and got the same behavior. Have not completely uninstalled app.

**Comment by francieisking999** [comment]
I fixed it first u download the previous release https://github.com/mtaheij/PoGo-UWP/releases/tag/v1.2.9-beta
Then u install it
Put in your hashing key
U should see the log in screen
Now go out od the app
Uninstall the old version
Reinstall the new version
Now it should sign in fine YouTube video coming soon

**Comment by francieisking999** [comment]
https://mobile.twitter.com/mccools2013proof its working again

**Comment by francieisking999** [comment]
The only thing that causes it to crash is battles if u try and join a battle the app crashes

**Comment by francieisking999** [comment]
Has worked great for me since doing the above method

**Comment by mtaheij** [comment]
Thank you for figuring this out!
I think it has to do with the AuthKey schema that has changed in the 1.2.10 version since we are now using POGOLib and it stores the AuthKey somewhat different.
Next version will do a check that invalidates older AuthKey instances and send you to the login screen.

**Comment by francieisking999** [comment]
Only thing that happens is sometimes it freezes and logs out not that annoying great app has come along way since June 2016

**Comment by mtaheij** [comment]
Yes, first priority was to enable the app again. Now, we can further investigate the issues again.
Battles are not complete yet, I thought I left them out but something might have slipped in.

Thanks for you support!

**Comment by BadiBasso** [comment]
Does not work for me. App starts updating from .9 to .10 as soon as I launch it. Never have chance to add hash key with .09

**Comment by porscheguy** [comment]
@francieisking999 

Worked for me, Thanks.

**Comment by BadiBasso** [comment]
Works now ):
Disconnected from network when update was in progress, reconnected, inserted hash key, logged in, answered no to all dialogs, got to map, logged off and closed the app. Restarted, let the app update and logged in.

**Comment by BadiBasso** [comment]
Will have a pristine Lumia 650 to test with later this evening. I'll post the results when available.

**Comment by Kamiako** [comment]
Went through the steps people are recommending was able to get to the login screen on 1.2.10 but i get the error message when trying to login with PTC account and reloading the app gets me back to the infinite load splash screen.

**Comment by andremvm** [comment]
Since I updated to the new version today, I am getting an error saying that my hashing key is not valid, even though it was working properly before that... Any idea what went wrong?

**Comment by mtaheij** [comment]
Did your key expire? You can check the status on https://eu.buddyauth.com/User/Keys

**Comment by andremvm** [comment]
No, I got this one on March 1st, so I should have at least half a month left with it!

**Comment by mtaheij** [comment]
It can also be that the hashing server returns an incorrect result, as these servers are not very stable the last few days. There is some work to be done on the detection of pokehash errors and timeouts.

**Comment by andremvm** [comment]
Now, after uninstalling and re-installing the app 5 times, it started working again... It can indeed be that you are right and the problem was in the server!

**Comment by francieisking999** [comment]
No need to use my hack anymore a nee update was released yesterday 15th march it works fine

**Comment by andremvm** [comment]
Well, in order to avoid the problem of my non-valid hash key, I still used your hack... :)
