### ISSUE TITLE
Gym Battle UI

### ISSUE THREAD

**Issue by DarkLegend481** [mtaheij/PoGo-UWP#33]
Hey @mtaheij

Thanks to you and the others who also helped in version 1.2.11 of PoGo.

You're implementing Gym Battles, are not you? I found a site that contains .gifs of Pokémon and the best... They have transparent BGs !!

Here is the link: http://pokestadium.com/tools/sprites

If you want, as I have some time left I can download and compile these .gifs to make the battle less "static"...

If so, I'll close the issue UI Update and leave it open in place. If not, I'll close both, because for now we should worry about the resources, not so much with the UI...

**Comment by DarkLegend481** [comment]
Soon, I will help with code. I'm studying C#...

**Comment by ntaheij** [comment]
Can you please edit the link and make the é a normal e because, the link isn't clickable at the moment

**Comment by ntaheij** [comment]
And, they are .gifs, but they aren't the real pokemon go .gifs, they are the drawed types, but really nice that you found some :)

**Comment by DarkLegend481** [comment]
They are XY .gifs, but, have the same animations of Pokémon GO.

**Comment by DarkLegend481** [comment]
Link clickable now

**Comment by mtaheij** [comment]
Starting the gym battles...
![start_of_gym_training_battle](https://cloud.githubusercontent.com/assets/769923/24063285/58362e4a-0b5f-11e7-8a18-9e66168919c7.png)

**Comment by DarkLegend481** [comment]
Well... Did you want the .gifs? Or not?

**Comment by DarkLegend481** [comment]
Not wanting to put pressure on anything, but is that soon my college will start to get harder... And the time I wait for the answer, I could be downloading the .gifs...

**Comment by mtaheij** [comment]
I'm not sure if the gifs can be used. They have to be at least with a transparent background (I've seen some on that site  are, but not all).
Besides that, we will have to include all gifs in the package, and that will increase the download and installed size dramatically.
I prefer to do the animations in Unity later, but that will take a long time to investigate. I will try this weekend using one of the gifs in the pokemon detail view.

**Comment by DarkLegend481** [comment]
OK! I will keep this issue open... If something happens, I will post here.

**Comment by mtaheij** [comment]
This is how it could look: [Animated gif in POGO-UWP](https://youtu.be/8lL2n04GkCo)

The animated gifs are quite small, so they look a bit blocky when enlarged.
Besides that, 250 pokemons * 5 animations * 100kb (roughly) = 120 Mb
Don't know how this will be stored in the package, but it will increase the download and install size dramatically.
What shall we do?
I suggest we deal with battling using static images first and take a look at Unity later.

**Comment by BadiBasso** [comment]
Using local app data cache might do it. Load gifs only when they are needed.
https://docs.microsoft.com/en-us/windows/uwp/app-settings/store-and-retrieve-app-data

**Comment by BrazilianBug** [comment]
@mtaheij  https://github.com/mtaheijIf you want to replace the .png by .gif you can get the .gif files that I downloaded from the site "http://pokestadium.com/tools/sprites" in this file there are even 278 Pokemons

https://www.mediafire.com/?2g028uus5yr6qqn

**Comment by DarkLegend481** [comment]
@BrazilianBug That's exactly it ... But why 278 Pokémon? The first generation and the second together are 251.
@BadiBasso I thought of suggesting this as I remembered that Niantic stores the Pokémon GO models on their servers. I thought about storing the .gifs on some server, but I'd forgotten AppData...

**Comment by DarkLegend481** [comment]
@BrazilianBug Sorry, I spelled "exactly it...", but no, my original plan it's add .gifs! We will need .png for Pokémon Page, Map and Nearby. 😉

**Comment by ntaheij** [comment]
Probably this is enough, if not, please reopen the issue
