### ISSUE TITLE
Unable to log in with Google Account

### ISSUE THREAD

**Issue by DrMabuse90** [mtaheij/PoGo-UWP#35]
Device info
------------------
- Phone type: Lumia 950 XL and PC
- App version: 1.2.11

Steps to reproduce
----------------
Remove app
Install app from scratch
Enter pokehash key
Login with Google

Actual behavior
-----------------
Received "Something went wrong and app may be unstable now. Do you want to logout and try again?"

Expected behavior
---------------
Log in

Other information
---------------
Clicking yes goes back to the alert with something went wrong. If you click no the app remains on the Login screen.

No Problems logging in with PTC account

**Comment by PROATLION** [comment]
I've been getting this message for like 1.5 weeks now. I tried to login via my iPad and I get a message saying "Error cannot get game data from server." I feel like our accounts are locked or soft banned

**Comment by DrMabuse90** [comment]
But i can login via my Android device without problems

**Comment by DrMabuse90** [comment]
I also noticed that when im logged in with my PTC, logout and then try to log in with my Google account, i still get logged in with my PTC account

**Comment by mtaheij** [comment]
I have no problems logging in using a Google account myself.
Did a small change for the next version however, to let the app really 'forget' the username and password. That should help switching from one to another account.

**Comment by DrMabuse90** [comment]
Tried it on 3 different phones with multiple Google accounts, always the same Problem. Obviously it's not Account related.
Installed app on all phones from scratch with no older pogo version installed before

**Comment by ntaheij** [comment]
Same thing. Because it reminds some things like passwords etc.

**Comment by Darknoz** [comment]
I have same error (PTC account):

http://www.kepfeltoltes.eu/view.php?filename=504wp_ss_20170317_0001.png

http://www.kepfeltoltes.eu/view.php?filename=188wp_ss_20170317_0002.png

**Comment by mtaheij** [comment]
This should be fixed in the next release (code will be available later today).

**Comment by DrMabuse90** [comment]
Later today?

**Comment by mtaheij** [comment]
Yes, the code is available, check the Gym_Battle branch.
A release will follow as soon as I get a working gym battle.

**Comment by DrMabuse90** [comment]
Hmm strange, works fine for me now since 1.3.0

**Comment by Rokuzer** [comment]
what u do for work?

**Comment by DrMabuse90** [comment]
Nothing special
