### ISSUE TITLE
Improve Translations

### ISSUE THREAD

**Issue by DarkLegend481** [mtaheij/PoGo-UWP#36]
I can provide Portuguese translations of PoGo words and phrases... Other languages... Google Translate can be used.

**Comment by DarkLegend481** [comment]
PT-BR Translations:

• Pinap Berry - Alimente um Pokémon com isto e faça o largar mais doces.
• Troy Disc - Um módulo que atrai Pokémon para um PokéStop por 30 min. O efeito também beneficia outras pessoas por perto.
• Lucky Egg - Um Ovo da Sorte recheado com alegria! Duplica o XP recebido por 30 min.

**Comment by DarkLegend481** [comment]
• Potion (same but HP number changes)

**Comment by DarkLegend481** [comment]
• Up-Grade:
EN-US - A transparent device that can make certain species of Pokémon evolve. It was produced by Silph Co.

PT-BR - Um dispositivo transparente que faz certas espécies de Pokémon evoluir. Foi produzido pela Silph Co.

**Comment by DarkLegend481** [comment]
Metal Coat/Revestimento de Metal:

EN-US - A coating that can make certain species of Pokémon evolve. It is a special metallic film.

PT-BR - Um revestimento que faz certas espécies de Pokémon evoluir. Ele é um filme metálico especial.

**Comment by DarkLegend481** [comment]
• King's Rock/Rocha do Rei:

EN-US - A rock that can make certain species of Pokémon evolve. It looks like a crown.

PT-BR - Uma rocha que faz certas espécies de Pokémon evoluir. Ele parece com uma coroa.

**Comment by DarkLegend481** [comment]
• Dragon Scale/Escama de Dragão:

EN-US - A scale that can make certain species of Pokémon evolve. It is very tough and inflexible.

PT-BR - Uma escama que faz certas espécies de Pokémon evoluir. É muito resistente e inflexível.

**Comment by ntaheij** [comment]
If you want you can do it yourself

**Comment by DarkLegend481** [comment]
But how?

**Comment by mtaheij** [comment]
Yes, it's a nice try, but it will take too much time for us to take all these translations from here and put them in the repo.
If you take a little learning in Github/Visual studio/MultiLingual App Toolkit, you can create Pull Requests for these translations.

**Comment by DarkLegend481** [comment]
OK!

**Comment by ntaheij** [comment]
That is what i mean :)
