### ISSUE TITLE
Invalid HashKey Error

### ISSUE THREAD

**Issue by WanderingJesusFreak** [mtaheij/PoGo-UWP#37]
![wp_ss_20170318_0002](https://cloud.githubusercontent.com/assets/21267490/24077104/8d4ecd26-0c18-11e7-97d1-38810f6ae3ab.png)
Device info
------------------
- Phone type: Lumia 950 XL
- App version: . 1.2.11

Steps to reproduce
----------------
Start the game.

Actual behavior
-----------------
The game starts and I get the two errors below in the screen shots.

Expected behavior
---------------
Game will start
P
Other information
---------------
I tried putting the has key in again and nothing happened.
![wp_ss_20170318_0001](https://cloud.githubusercontent.com/assets/21267490/24077102/846b0fb2-0c18-11e7-93dc-3372cfb711bd.png)

**Comment by WanderingJesusFreak** [comment]
FYI, it has done this twice and then worked about an hour or so later.

**Comment by mtaheij** [comment]
Turns out this is not a wrong hashing key, but the location initialization failed.
Restarting your phone can help in this case.
Message is shown correctly now.

**Comment by BadiBasso** [comment]
@mtaheij Can confirm. Was playing with my daughter when she got this error all of a sudden. We share the same key. My acc had no problems while she was getting this error. Within 10 mins or so her app started to work after numerous app restarts.

**Comment by WanderingJesusFreak** [comment]
I'm getting this error again, but with a different error before it. I have tried reinstalling. Error picture attached.

**Comment by mtaheij** [comment]
The hashing server has an expired SSL certificate at the moment, in the current version, this situation is not catched. I will try to handle with this error in POGOLib for the next release.

**Comment by BadiBasso** [comment]
What if using plain http with PoGo-UWP?
There is no other sensitive data passed save perhaps authkey, which changes periodically.
Not having to decipher SSL would lessen cpu usage and lenghtens battery life.

**Comment by mtaheij** [comment]
http without the SSL certificates worked today, so while everyone was moaning about not being able to map/scan/bot, I was perfectly able to develop gym battles further :-)
But the url for PokeHash is in POGOLib, so if we want to use it plain as it is from NuGet, this will not work.

POGOLib is not complete: Out of the box, there is no support for hatched eggs and some more stuff, so we still need a forked and tweaked version. The SSL issue is solved now, should we still switch to http?

**Comment by Aegasx3** [comment]
So when it will be fixed ? Can it be fixed ?

**Comment by mtaheij** [comment]
Yes, it will and can be fixed. No time to make a new release atm, however.
If you use the code from the repo, it will work.

**Comment by Aegasx3** [comment]
What do you  mean with repo code ? I tried the workaround from #32 but it didn't worked. Im totally blocked out by the app tried to restart to see if it's maybe the location bug but after passing the buddyauth step and trying to log in it throws me out again.

**Comment by mtaheij** [comment]
Repo code = the code from github. You can download it and open it in Visual Studio to compile it yourself.
It's an advanced way of getting it to run, but you need some skills in programming to do it.
