### ISSUE TITLE
Berry Issue

### ISSUE THREAD

**Issue by Dragoncat4** [mtaheij/PoGo-UWP#38]
Steps to reproduce
----------------
Throw a berry (in my case pinap berry).

Actual behavior
-----------------
Berry is cast, but simultaneously pokeball is thrown. While the additional candies were awarded, I'm concerned that throwing both is an issue.

Expected behavior
---------------
Berry is cast alone and then additional action can be applied.

Other information
---------------

**Comment by mtaheij** [comment]
Where did you find that a pokeball is thrown simultaneously? The request when throwing a berry is a separate request. It selects an available Pokeball directly, but does not throw one.

**Comment by Dragoncat4** [comment]
I throw a pinap berry. Next thing a pokemon was caught.

**Comment by mtaheij** [comment]
Do you have pinap berries in your inventory before throwing?
Could it be that you are selecting a Pinap berry for throwing, but you are out of them? May be it shows as a pinap berry being throwed, but a Pokeball is used in the back end?
From the code, it's impossible to throw a Pinap berry and a Pokeball at the same time.

**Comment by Dragoncat4** [comment]
There is a small issue of items changing its places, that true. However I did get an increased number of candies, so the event of pinap berry throw had to take place. 
It was just one case (I did not repeat it), will try again to ensure the repeatability of the issue.

**Comment by Dragoncat4** [comment]
OK, I tested it several times and seems OK. Probably was just one of those situations when certain unrepeatable actions were chained resulting in such situation. Closing.
