### ISSUE TITLE
Question / suggestion [SplashScreen]

### ISSUE THREAD

**Issue by BrazilianBug** [mtaheij/PoGo-UWP#39]
(Sorry for my English)
![pogo logo full](https://cloud.githubusercontent.com/assets/21015826/24086963/42a70c2c-0cf7-11e7-9e8f-b27f783d5bb1.png)

I have a question, would it be possible to make a new "SplashScreen" that is part of the Loading Screen of the game? In this way it would be possible to remove the "SplashScreen" Standard from Visual Studio and make the application go directly to the loading screen that is the new "SplashScreen" and that would then present the Loading screen

(Below the example of how it would be)
![exemplo](https://cloud.githubusercontent.com/assets/21015826/24087157/376465c8-0cfa-11e7-9bb3-854180b445eb.png)

My problem: If I can do this I would be happy to send all the new "SplashScreens" in the necessary resolutions, so far I have only done in this resolution to exemplify.

I do not know enough to make a code that solves this question, but I try to help in any way I can.

Thank you for your attention, Below, Text in Portuguese (PT-BR)

(Desculpe pelo meu inglês)

Tenho uma pergunta, Seria possivel fazer uma nova "SplashScreen" que seja parte da Tela de Loading do jogo? Desta forma seria possivel remover a "SplashScreen" Padrão do Visual Studio e fazer o aplicativo ir direto para a tela de loading que seja a a nova "SplashScreen" e que em seguida apresenteria a tela de Loading

(Abaixo exemplo de como seria)

Minha sujestão: Se puder fazer isso eu ficaria feliz em enviar todas as novas "SplashScreens" na resoluções necessarias, por enquanto fiz apenas nesta resolução para exemplificar.

Não tenho conhecimento o suficiente para fazer um codigo que resolva esta questão, porem tento ajudar das formas que posso.

Obrigado pela atenção, Abaixo, Texto em portugues (PT-BR)

**Comment by ntaheij** [comment]
This is already done so far, or not?

**Comment by ntaheij** [comment]
Only the begin splash screen is a bit diffrent

**Comment by BrazilianBug** [comment]
Unfortunately I do not have the knowledge to design this, what I am proposing is that in the example the "after" part is an example of how it could be, this Loading Screen from the "after" example I removed from the internet only with the function To illustrate, but this image of Splash Screen I realmene did, however, it was just the image.

If anyone wants to create a New Splash Screen to replace the default Splash Screen from Visual Studio, I'd be happy to contribute Splash Screen images to whatever resolutions are required.

Text in Portuguese (PT-BR)

Infelizmente eu não tenho o conhecimento para projetar isso, o que estou propondo é que , no exemplo a parte de "depois" é um exemplo de como poderia ser, esta Loading Screen do exemplo de "depois" eu retirei da internet apenas com a função de ilustrar, porem esta imagem de Splash Screen eu realmene fiz, porem, foi apenas a imagem.

Se alguém quiser criar criar uma Nova Splash Screen para substituir a Splash Screen padrão do Visual Studio eu ficaria felizem contribuir com as imagens de Splash Screen nas resoluções que forem necessarias.

**Comment by mtaheij** [comment]
In the 'after' part, the Splash screen will be replaced by the Unity splash screen in a later phase.
Don't you see the 'loading screen' at all? I can see it just after the splash screen.

**Comment by BrazilianBug** [comment]
@mtaheij Here no longer appears the Loading Screen, I thought you had intentionally removed, would it be a bug then?

**Comment by BrazilianBug** [comment]
Sorry, there is no bug, the loading screen appears for min, below example corrected
![exemplo2](https://cloud.githubusercontent.com/assets/21015826/24158713/d617a1c0-0e3b-11e7-877e-e84b24abf981.png)

**Comment by ntaheij** [comment]
Solved. If not please reopen issue
