### ISSUE TITLE
Phone not installing app

### ISSUE THREAD

**Issue by Thedeveloperfairy** [mtaheij/PoGo-UWP#4]
My phone will not install pokemon go

my phone is Microsoft Lumia 950xl

**Comment by mtaheij** [comment]
Did you check the Wiki, about how to install it?
Is there an error message?

**Comment by DarkLegend481** [comment]
Method 1: Rename it from .appxbundle to .appx and install.
Method 2: Install using Interop Tools
Method 3: Device Portal

**Comment by Thedeveloperfairy** [comment]
Failure reason: An internal error occurred with error 0x80073D05. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.. Failure text: An error occurred while deleting the package's previously existing application data. (0x80073d05)

**Comment by Thedeveloperfairy** [comment]
Hey sorry for wasting time I need to restart my phone

**Comment by Thedeveloperfairy** [comment]
its installed now thank you for your help

I currently at uni studying Computer Science and I would like to help but I would need to be help with learning the syntax how how I would use it to do something like this

**Comment by mtaheij** [comment]
Thanks for reporting back. Have fun!
