### ISSUE TITLE
help😰 

### ISSUE THREAD

**Issue by FooiaZaiats** [mtaheij/PoGo-UWP#42]
Don't working. Splash screen (perhaps 30 sec.) and it crashes.
Device info

- Phone type: Lumia 550
- App version: 1.2.11

Steps to reproduce
I want to know them.

Actual behavior
CRASH!!!

Expected behavior
It must work.

Other information
Why did you close issues like this without answer? Is it a bug only at Lumia 550? If you can help, write instructions in Readme.

**Comment by RSikkel** [comment]
Did you try fully removing the app and installing it again?

**Comment by FooiaZaiats** [comment]
Yes, of course. Crashes again.

**Comment by FooiaZaiats** [comment]
I can reinstall it again.

**Comment by RSikkel** [comment]
And you don't get any error messages? You can try removing the app, installing this version https://github.com/mtaheij/PoGo-UWP/releases/tag/v1.2.8-beta, then enable error reporting without upgrading, then upgrade

**Comment by FooiaZaiats** [comment]
I can't enter the old version (1.2.80), too.

**Comment by BadiBasso** [comment]
@FooiaZaiats what is your windows version? I had two phones (Lumia 435 and 650) with original build 10586. App installed fine but crashed at start. Upgraded both to 14393 (AU) and now app is running fine on both.

**Comment by FooiaZaiats** [comment]
10586? I have this! I need to update, I think?

**Comment by BadiBasso** [comment]
Based on my experience: Yes, 14393 is needed.
If someone has app running on 10586, that I do not know.

**Comment by FooiaZaiats** [comment]
Thanks, now its working 😀

**Comment by mtaheij** [comment]
Added this requirement to the WiKi pages.
Windows 10 build 14393 - Anniversary Update - is indeed the minimum required build number.
