### ISSUE TITLE
Adding 3d models

### ISSUE THREAD

**Issue by RSikkel** [mtaheij/PoGo-UWP#43]
I know this is not likely to happen and will take a lot of work, but maybe it would be possible? 

https://github.com/PoGo-Devs/PoGo-3D-Assets
https://github.com/MadoxLabs/PoGo-UWP

**Comment by RSikkel** [comment]
Great to hear! Things really took off after you took over the project!

**Comment by Avid29** [comment]
I'm one of the artists/developers that was on this project before. I'm glad to see we're getting back to it. It's also important to keep in mind that all but one of them (Seaking, made by me) were acquired online. It's also extremely to difficult to implement things like particles and flame in SharpDx so we'd probably want to adapt it to Unity which would take a ton of effort.

**Comment by BrazilianBug** [comment]
Is it easier to put 3D models without animation? I particu- larly think it would be much more interactive to capture the pokemon on a 3D screen, even if it only stays fixed, no animations and no effects, just the 3D model with the texture

**Comment by Avid29** [comment]
Yes, overtime we could put together fun animations for them but at the moment it is really difficult to cover them all when it's not your job

**Comment by Avid29** [comment]
Still keep in mind flames and particles though

**Comment by DarkLegend481** [comment]
Maybe... We can use particles from Pokémon X/Y, OR/AS or Sun and Moon...

**Comment by Avid29** [comment]
Making them isn't an issue. Rendering them is

**Comment by BadiBasso** [comment]
Has anyone taken a look of this: https://www.reddit.com/r/pokemongodev/comments/4xh1gs/how_pokemon_3d_models_are_decrypted/
Wonder if it's still applicable.

**Comment by ntaheij** [comment]
We don't need 3d models atm, when we do it, we probably do it with Unity. :)
