### ISSUE TITLE
volume of background music lowers when opening pogo app

### ISSUE THREAD

**Issue by RSikkel** [mtaheij/PoGo-UWP#44]
Device info
------------------
- Phone type:  Lumia 950 XL
- App version: 1.2.10

Steps to reproduce
----------------
Start background music, open app

Actual behavior
-----------------
Music volume is lowered

Expected behavior
---------------
Music volume stays the same

Other information
---------------
Didnt test on speakers so far, only with headphones.

**Comment by WanderingJesusFreak** [comment]
I've noticed this also happens every time the map updates for me. However, if I turn the volume up or down, it goes back to the original volume first (gets louder). It will then lower again when the map updates. This behavior is sporadic though.

**Comment by ntaheij** [comment]
Solved. If not please reopen issue

**Comment by WanderingJesusFreak** [comment]
What version is the solution in? I still get the symptoms in 1.3.2.
