### ISSUE TITLE
Is it safe now to play or still not?

### ISSUE THREAD

**Issue by Kao90** [mtaheij/PoGo-UWP#45]
Hi everyone,
With one of the previous versions of pogo, captcha was not allowed and I was banned permanently. Is this version secure to play? Are there any risks about or not anymore?
Thanks

Device info
------------------
- Phone type: Lumia 950 
- App version: (e.g. 1.2.10)

**Comment by mtaheij** [comment]
It has never been really safe to use another client than the official app by Niantic. But as they refuse to make one for Windows Mobile, we have created our own.
Since the last release, I've never seen one (!) captcha.

**Comment by andremvm** [comment]
I had several captchas on the previous version of the app, now none (and I have been using the app a lot!) and still my account wasn't banned... maybe I was too lucky so far!

**Comment by Kao90** [comment]
But to play with this version I need the key...it was free, wasn't it?

**Comment by BadiBasso** [comment]
PoGo-UWP in itself is free to use but it needs paid service to work. Please read: https://github.com/mtaheij/PoGo-UWP/blob/master/README.md
At the moment there are no other options to play.

**Comment by BadiBasso** [comment]
The cheapest hashing key can be used in multiple clients. Should be enough for 4-5 in normal playing.
