### ISSUE TITLE
Can't auth myself.

### ISSUE THREAD

**Issue by Aegasx3** [mtaheij/PoGo-UWP#46]
Device info
------------------
- Phone type: (e.g. Lumia 950 XL)
- App version: (e.g. 1.2.11.0)

Steps to reproduce
----------------
Write in the hashing key.

Actual behavior
-----------------
Short loading time then a pop up with "It seems that this is not a valid hashing key"

Expected behavior
---------------

Other information
---------------
I asked the bossland support they say there's no problem with the key its valid.

**Comment by BadiBasso** [comment]
Known issue. Please take a look at #37
