### ISSUE TITLE
i can't log with Google Account! HELP ME PLEASE

### ISSUE THREAD

**Issue by Rokuzer** [mtaheij/PoGo-UWP#48]
![wp_ss_20170327_0001](https://cloud.githubusercontent.com/assets/26714315/24373319/43e80d76-1331-11e7-8504-15e1597418fb.png)

Device info
------------------
- Phone type: Lumia 830
- App version: 1.3.0

To log in to google account, i see "Something went wrong and can be unstable, exit and try again"

**Comment by ntaheij** [comment]
Probably #35 will help you a bit.

**Comment by Rokuzer** [comment]
dat not helped me :( it no solved in #35 :(

**Comment by mtaheij** [comment]
Can you create a (temporary) PTC account using the link between the PTC login and Google login button?
If you login using that account, does it work?
After that, go to pokeball menu -> settings -> sign out, deselect the 'remember me' checkbox and quit the app using the back button from your phone.
Then, start the app again and try to log in using your Google account again.

Hope this works.
I have no problems signing in using a Google account, so it is supported, works like a charm.

**Comment by Rokuzer** [comment]
i tried that with 2 PT account one new, and remains exactly the same, the same error with my google account, but with PT account Login succesfull

**Comment by ntaheij** [comment]
Did you try to uninstall the app?

**Comment by Rokuzer** [comment]
Yes, and same problema :(

**Comment by ntaheij** [comment]
No mistakes in the email and password

**Comment by ntaheij** [comment]
What is your language if i can ask?

**Comment by Rokuzer** [comment]
Spanish

**Comment by Rokuzer** [comment]
and not, not error in password

**Comment by Rokuzer** [comment]
Now it work fine! Thx i reset, put idiom english, and connect

**Comment by mtaheij** [comment]
Did you set your phone to English? What was the complete solution? It might help getting it fixed...

**Comment by Rokuzer** [comment]
I set the aplication in english, i connect with PT account and now set english in idioms then disconect, close app and reset phone, now can connect with google account.

**Comment by mtaheij** [comment]
Ok, thanks! I will try and look for a solution that doesn't need this workaround.

Have fun!

**Comment by Rokuzer** [comment]
Thx u ^^

**Comment by ntaheij** [comment]
Solved. :)
