### ISSUE TITLE
issue with the authorization key

### ISSUE THREAD

**Issue by hawiley2256** [mtaheij/PoGo-UWP#50]
Device info
------------------
- Phone type: Lumia 640xl
- App version: 1.3

I pull up the app and it pulls up the window where you enter the authentication key. I enter it and it pulls up a window that says arg_nullreferenceexception and that's it. It has done this before but the there is usually some loading then it gives this error with a bunch if extra stuff I restart the app or phone and it fixes it this time none of that fixes it.

**Comment by Aegasx3** [comment]
I had the problem too. But it accepts the hash key if im not in the wlan.

**Comment by ntaheij** [comment]
Did you read other issues about this?

**Comment by ntaheij** [comment]
I dont really know but the key need to be UPPERCASE, and er is a change that the hashing server is down.

**Comment by andremvm** [comment]
Whenever I experience that issue in the new version it is because indeed the hashing server is down... You can check them here if needed: https://status.buddyauth.com/

**Comment by ntaheij** [comment]
I said that. But thanks for the link. That is the problem. Have a nice day :)

**Comment by DarkLegend481** [comment]
I downloaded 1.3.1 and I get this error:
![wp_ss_20170408_0001](https://cloud.githubusercontent.com/assets/22161127/24830019/d15a0012-1c53-11e7-923a-1c613caa862b.png)

How I fix it? (Already tried restart my phone...)

**Comment by mtaheij** [comment]
I assume you have entered a valid key. Did you also try to remove the app, then restart your phone and download/install it again?

**Comment by DarkLegend481** [comment]
Nope... I formatted my phone (memory issues...),n ow I will try install it again.

**Comment by DarkLegend481** [comment]
Hey @mtaheij, what you don't keep this issue open? If another problem happens, we don't need open another issue every time talking about the same problem...
