### ISSUE TITLE
Baby pokemon as buddy does not show in player details

### ISSUE THREAD

**Issue by BadiBasso** [mtaheij/PoGo-UWP#52]
Device info
------------------
- Phone type: All
- App version: Newest (1.3.0)

Steps to reproduce
----------------
Set baby pokemon as ypur buddy

Actual behavior
-----------------
Baby pokemon is not shown in palyer details page

Expected behavior
---------------
Baby pokemon shows in player details page with the player

Other information
---------------
Need to update converter for correct placement of baby pokemon as buddy.

**Comment by mtaheij** [comment]
Which pokemon do you refer to? Is it a 2nd gen pokemon? Which one?

**Comment by BadiBasso** [comment]
Babies which were introduced before Gen2: Togepi, Pichu, Magby, Elekid, Igglybuff, Smoochum and Cleffa.
Coded the converter before they were out and it's missing positioning of these

**Comment by BadiBasso** [comment]
New enum BUDDY_BABY of BuddySize in PokemonSettings

**Comment by BadiBasso** [comment]
Needs at some point a new avatar of player with arms folded:
[https://www.google.fi/search?q=pokemon+go+baby+buddy&prmd=ivns&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi7pMy8343TAhVBLMAKHVM3DcgQ_AUIBigB#mhpiv=0&spf=1](url)

**Comment by mtaheij** [comment]
We also need a female player Avatar image. Anyone who can make this (similar to the gif and png we have now)?
![avatar](https://cloud.githubusercontent.com/assets/769923/24717416/b41abc8a-1a32-11e7-90c3-7495b47431c9.gif)
![avatar](https://cloud.githubusercontent.com/assets/769923/24717417/b41b028a-1a32-11e7-9e8c-b79a29a12a9e.png)

**Comment by mtaheij** [comment]
Code is now made for a baby pokemon Buddy.
Will be in the next release.

**Comment by BadiBasso** [comment]
Now that was fast, I must say :)

**Comment by mtaheij** [comment]
Remaining open for now, so I don't forget to mention it in the release notes.
There is more to come in the coming release btw:
- Journal
- Gym battling (automatic)

**Comment by mtaheij** [comment]
Should be fixed in the 1.3.1 release. Can anyone check please? (I don't have a baby pokemon in my inventory)

**Comment by BadiBasso** [comment]
Can confirm that positioning is ok for my Togepi at least
