### ISSUE TITLE
Battery 🔋 Saver Bug

### ISSUE THREAD

**Issue by ntaheij** [mtaheij/PoGo-UWP#53]
Device info
------------------
- Phone type: idk
- App version: 1.3.0

Steps to reproduce
----------------
(Not if you already have)
Start Pogo
Enable Battery saver
Close app
-
Open Pogo
Do some things
Close the app

Actual behavior
-----------------
When app is closed, the Battery Saver still do it's work for 3 minutes or so.

Expected behavior
---------------
Battery Saver doesn't do it's work

Other information
---------------
-

**Comment by BadiBasso** [comment]
Does not apply to my phone. No screen blanking after Pogo is closed.

**Comment by ntaheij** [comment]
I've fixed it on my phone now

**Comment by ntaheij** [comment]
It is still not fixed, it only works after like a hour pr so

**Comment by ntaheij** [comment]
Or so*
