### ISSUE TITLE
Hasher version error

### ISSUE THREAD

**Issue by DavidWForeman** [mtaheij/PoGo-UWP#54]
The version of the Hasher (0.57.4) does not match the minimal API version of PokemonGo (0.59.0).  Set 'Configuration.IgnoreHashVersion' to true if you want to disable the version check.

Device info
------------------
- Phone type: Lumia 950 XL
- App version: 1.3.0

Steps to reproduce
----------------
Load App

Actual behavior
-----------------
Error Message above appears over the Store and Continue PokeHash entry screen

Expected behavior
---------------
App loads with no error.

Other information
---------------

**Comment by mtaheij** [comment]
This message means that the API used for communication with Niantic's server has changed.
It protects your trainer account because the hashing server discovered that we use an old API.
This is detected BEFORE any connection was made to Niantic.

It will however, require an update for the API we use. I will look for the changes in the API and release a new version.

**Comment by Rokuzer** [comment]
Same problem :(

**Comment by mtaheij** [comment]
There is no complete solution for now, without risking your trainer account being banned.
We have disabled the app until a solution is available.

**Comment by BadiBasso** [comment]
According to Pogodev discord issues have been resolved.
PoGo-UWP needs only updated API which is already available.
Been testing with private build and thus far have no errors.

**Comment by mtaheij** [comment]
Busy with that, almost done.

**Comment by BadiBasso** [comment]
Constant playing with two accounts for 1.5 hours. With no errors I trust the code is safe again.

**Comment by mtaheij** [comment]
I've added some more things (exception was thrown when Potion was used on a deployed pokemon and so on).

**Comment by BadiBasso** [comment]
Nice. I have worked on the new evolutions and GUI part is already mostly done. Was working on backend when API changed. Should be ready in a few days if I had enough time to spare.

**Comment by kev0200** [comment]
Silly question, does the app have automatic updates at all?

**Comment by mtaheij** [comment]
Yes, the app should automatically detect that there is a new update.

**Comment by mtaheij** [comment]
Release is out!

**Comment by BadiBasso** [comment]
Up to date splash screen? Really nice 👍

**Comment by DrMabuse90** [comment]
Will there be a x86 version too?

**Comment by mtaheij** [comment]
There is an x86 and x64 version now as well. Enjoy!

**Comment by WanderingJesusFreak** [comment]
This issue has returned

**Comment by Rokuzer** [comment]
Yah again wait xD

**Comment by mtaheij** [comment]
Not much has changed. Preparing a new release now!

**Comment by Diagoras14** [comment]
After new release i have "There seems to be something wrong with the hashing server" popup...

**Comment by mtaheij** [comment]
New release 1.3.2 is out.

**Comment by danmartinez16** [comment]
I updated to version 1.3.2 but I'm getting this "Failed parsing pokehash response headers" when open the app
