### ISSUE TITLE
Graphic issues with new version 1.32

### ISSUE THREAD

**Issue by DavidWForeman** [mtaheij/PoGo-UWP#58]
Device info
------------------
- Phone type: 950 XL
- App version: 1.32.0

Steps to reproduce
----------------
Usage

Actual behavior
-----------------
Random graphics appear - graphics appear very unstable.
I have seen large images of poke balls and pokemon when going into a wild pokemon screen

Maps do not appear initially or can appear but zoomed way out.
Sometimes blank sometimes zoomed out plus other artifacts on the map screen.
Zooming doesn't appear to work either.

There is also a problem that when in isometric view the tracking is off.

Expected behavior
---------------
Only relevant graphics appear in the correct zoom.

Map appears in the correct zoom

You are able to Zoom in and out to display more of the map when necessary.

Tracking remains on when in isometric (as opposed to top down?) mode.

Other information
---------------
See image for example.  I will collect others as I see them.
![wp_ss_20170410_0001](https://cloud.githubusercontent.com/assets/12512656/24843169/92f6ad3e-1de3-11e7-9b0a-7cd50ed3270b.png)

**Comment by ntaheij** [comment]
It's really weird, but you're one of the first that can login, perhaps you can help with the issues where people say they can't login

**Comment by DrMabuse90** [comment]
I guess you are on Windows 10 Insider Preview Build 15063.2 (saw that because of the new map layout).
I have the same problem, but its not a problem of PoGo 1.32. I think its a general problem with build 15063 and its new version of the map app.

**Comment by ntaheij** [comment]
Yea.. I think that's it.. Because I get the old map

**Comment by BadiBasso** [comment]
MS has changed XAML rendering in December Preview Build:
https://blogs.windows.com/windowsexperience/2016/12/01/announcing-windows-10-insider-preview-build-14977-mobile/#JspkLyHmr8OZSEJV.97
My phone is running preview builds and I've seen these display glitches ever since.

**Comment by ntaheij** [comment]
There is your answer, no glitch/bugg in PoGo

**Comment by DavidWForeman** [comment]
Thanks - that does make sense as it isn't necessarily consistent.  Just weird that I get various graphical anomalies.  But it could well be the rendering.  If people are still getting login problems then perhaps they need to update(purchase renewal) their pokehash (it only last 31 days).

**Comment by DarkLegend481** [comment]
@DavidWForeman How you logged in? I tried 3 valid keys and I always recive errors... :-(

**Comment by DavidWForeman** [comment]
I have noticed that at various times a day I get pokehash errors but the resolve within 30 minutes.  I have put it down to a server error with the pokehash server.  For the record I use a PTC login.  I have also notice from time to time I get what appears to be an indication that the 150 /m requests have been exceeded.

**Comment by mtaheij** [comment]
When the 150RPM has been exceeded, the app will look like it 'hangs' at the moment. The internal workings of the hashing part in POGOLib is that it will display 'holding key selection' in the debugger output and it will sleep the thread for about 60 seconds. But as the app does not work in debug mode on your phone, it will not display the message. The sleep however will still be there. I hope to find a solution to let the user know about this sleep in the next version.
