### ISSUE TITLE
Fail to power up

### ISSUE THREAD

**Issue by Rokuzer** [mtaheij/PoGo-UWP#59]
Device info
------------------
- Phone type: Lumia 830
- App version: 1.3.2

Steps to reproduce
----------------
When i pulse power up not aument the status and not power up anything i think that is a bug i prove with various pokemon.

Actual behavior
-----------------

Expected behavior
---------------

Other information
---------------

**Comment by Rokuzer** [comment]
I prove again and only work first time to power up need close and open pokemon bault

**Comment by ntaheij** [comment]
This is a well known issue, and we will probably fix this later
