### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by Jao78** [mtaheij/PoGo-UWP#6]
The application may be unstable 
Wanna go out ?

**Comment by BadiBasso** [comment]
Sorry, but you need to be more spesific.
At least information concerning your sex, age, profession and annual salary are needed before possible answer to your question.

**Comment by mtaheij** [comment]
Yes/No...

Whatever you like. What do you mean? Is this an error? A question? You have to provide me with some more information before I can say anything usefull.

**Comment by Malavos** [comment]
@Jao78  what language can you properly ask a question?

If it's portuguese, go ahead, I might be able to help. I might be able to help in spanish as well.

**Comment by Jao78** [comment]
Desculpe
Quando abri o pogo
Fiz o login e aparece que o app esta instavel
Por favor
Responda em PT-BR

**Comment by DarkLegend481** [comment]
Cara, se não funfar, tenta desinstalar e instalar denovo

**Comment by Malavos** [comment]
@DarkLegend481  a api não está off?

@Jao78  é necessário comprar uma chave agora, por conta que a API descriptografada ainda não foi publicada.

Tome cuidado ao criar issues aqui que não sejam no formato que eles especificam aqui. É melhor usar o reddit pra esse tipo de pergunta.

**Comment by DarkLegend481** [comment]
@Malavos 
![wp_ss_20170201_0001](https://cloud.githubusercontent.com/assets/22161127/22517677/1da0388e-e891-11e6-8d7e-06fde8066ad7.png)

**Comment by DarkLegend481** [comment]
Acabei de tirar esta screenshot

**Comment by Malavos** [comment]
@DarkLegend481  você já não usava antes? Eu te via aqui faz um bom tempo o.o ele é new user, a situação dele vai ser diferente, não?

Fiquei ausente faz um bom tempo, mas pelo que eu entendi, é isso

**Comment by DarkLegend481** [comment]
@Malavos Poderia me explicar melhor o que quis dizer?

**Comment by Malavos** [comment]
Claro. Eu vi a notificação do Github, e procurei no reddit news.
[Vi isso aqui.](https://www.reddit.com/r/PoGoUWP/comments/5r88ji/heres_whats_going_on_with_pogouwp/)

Eu não conferi os commits ou testei, então estou comentando com base nessas informações que eu li. Posso estar errado, lógico. Lê e me fala. :thinking:

**Comment by DarkLegend481** [comment]
@Malavos O jogo funciona, apenas necessita da chave PokéHash para o funcionamento dele.

A API não está off, apenas não foi liberada gratuitamente ao público. 
Esta versão tem um suporte Hashserver que permite a conexão com a API e faz o jogo funcionar.

Como eu não entendo inglês muito bem, tentei explicar o que entendi...

**Comment by DarkLegend481** [comment]
@mtaheij The key I use can be used in more than one session, I tested it with my mother, my brother and I, all using the same key.

**Comment by Malavos** [comment]
@DarkLegend481  então, é isso que eu falei. A api que a gente usava já foi pro espaço, e agora mtaheij, está usando a chave dele com essa api "privada". :thinking:  não é isso?

Mas enfim, eu acho que o @Jao78  pode tentar desinstar pelo device portal do WP. O que tu acha?

**Comment by DarkLegend481** [comment]
Ele apenas usa o hash da API, o código dele ele comprou...

O @Jao78 pode desinstalar normalmente e instalar nestes métodos:
• Interop Tools
• Device Portal + Dependências
• Renomear de .appxbundle para .appx e instalar pelo Explorador de Arquivos.

Todos estes eu testei e funfam. 😉

**Comment by Malavos** [comment]
Então, isso que quis dizer mesmo. 

Sobre o @Jao78  morreu?
Pelo que entendi, além dele querer sair com a gente.. :rofl: , ele fez uma fresh install. :thinking:  Esperar ele comentar aqui para ajudar, ou fechar se precisar.

**Comment by DarkLegend481** [comment]
Enquanto isso, dá pra nós conversar sobre o aplicativo em si... 🤔

**Comment by DarkLegend481** [comment]
Tipo...
Se você olhar nas PRs do repositório original do PoGo, um dos desenvolvedores, tinha adicionado o suporte aos ginásios, mas isso nunca foi implementado para todos... Por que será?

**Comment by DarkLegend481** [comment]
Fora que nos arquivos do jogo, isso também está implementado...

**Comment by Malavos** [comment]
@DarkLegend481  deve ser por quê lutas no ginásio são red flags pra niantic, não? Podem ser motivos de report. Afinal de contas, para alguns jogadores de droid e iOs, isso é importante, e se eles verem alguém com WP tirando eles do ginásios... vão chorar. hehahah tinha uma issue com essa discussão. acho que é isso.

**Comment by DarkLegend481** [comment]
Hahahah, mas tp, PoGo simula o iOS, não?

**Comment by DarkLegend481** [comment]
Porquê, se ele simula, a Niantic nn pode fazer nada, pois seria como um iOS user e nn um W10M...

**Comment by Malavos** [comment]
@DarkLegend481  simula sim, mas a API deles não precisa de um DeviceID? Device ID é único, e na Apple, o padrão dele é um. Se é um "iOs", e um deviceId que não se assemalha a um iOs.. bingo!

Eles baniram vários usuários que usaram pogouwp. Aí me perguntava porquê e suponho que seja por isso, no? :thinking:

**Comment by DarkLegend481** [comment]
Pois é, agora q vc disse isso...

**Comment by Malavos** [comment]
@DarkLegend481  olha na rocketApi ahahah

`public const string DeviceId = "cool-device-id";`

**Comment by DarkLegend481** [comment]
Kkkkkkkkkkkkkk bem que poderiam converter o ID de anuncio de cada Lumia ou PC para um DeviceID exclusivo....

**Comment by Malavos** [comment]
Mais fácil usar só o device ID mesmo, não? 

Algo Assim:
`DeviceExtendedProperties.GetValue("DeviceUniqueId")`

**Comment by DarkLegend481** [comment]
Então, se é só fazer isso, porque não implementam?

**Comment by DarkLegend481** [comment]
Não tem logica não adicionar isso, seria muito melhor, a taxa de ban provavelmente seria gratificantemente reduzida!

**Comment by Malavos** [comment]
No idea. :thinking:  Vou pesquisar aqui, se achar algo, comento

**Comment by Jao78** [comment]
Hey gente
Quando coloco a chave hash
Logo na minha conta do PTC
E da app instável
Poderia me ajudar-?

**Comment by Jao78** [comment]
Me chamem no whats
Para melhor me ajudar
48 996454043

**Comment by andremvm** [comment]
After 1 week of using the app, I can report that everything seems to be working fine in my Lumia 640 DS. I will download now the new version (new forced update) and will keep you guys posted about any possible things not working.
Sometimes I do get the error that something changed and the app is unstable so I should log out and log in again. Usually I select "no" unless the warning keeps coming up and makes it impossible to play. What I can say about this error is that basically happens every time there is something wrong with my internet connection (either is switching from 3G to WIFI or vice-versa, or whenever the phone connects to a different AP at the university), so that might be the only reason.
Sadly I do not have the skills to help you guys with the coding (unless somebody points me to a good start page), but I can help with beta testing stuff and whatnot, in case it is needed!

Once again, thanks for not letting this app go down.

**Comment by andremvm** [comment]
Well, just installed the new version and it worked fine for like 5 minutes. Then I switched off the app, and when I started it again I got the warning that the API level has been raised above what we have access. Any ideas why I was able to play for a short while until the app was closed?

**Comment by Malavos** [comment]
@andremvm I don't know at this moment. I'll check on that later.

@DarkLegend481  do we store logs on that?

**Comment by DarkLegend481** [comment]
@Malavos Cara, fala em português pfv... Eu nn entendi nada...

**Comment by andremvm** [comment]
@Jao78 , não pode logar na mesma com a app instavel? Tente clicar em "no" quando perguntar se você quer fazer logout. E cheque sua conexão à internet, geralmente o erro vem daí...

@DarkLegend481 , penso que o Malavos está a perguntar se vocês guardam os logs dos erros...

**Comment by Malavos** [comment]
Sim, eu estou.

Sent from my Windows 10 phone

**Comment by DarkLegend481** [comment]
@andremvm @Malavos Eu (por enquanto), não tive nenhum erro...

**Comment by DarkLegend481** [comment]
E nn tenho nenhum log de erro.

**Comment by DarkLegend481** [comment]
Alguém pode me dizer como os .gifs funcionam no PoGo? Sei q o avatar (Player Page), é em .gif... Mas quero ter certeza que não vai ter aqueles erros borrados...

**Comment by DarkLegend481** [comment]
É que eu estou trabalhando nisso agora...
![wp_ss_20170207_0001](https://cloud.githubusercontent.com/assets/22161127/22691344/2a74679e-ed21-11e6-8552-9e72367df162.png)

**Comment by andremvm** [comment]
Tal como eu disse, o meu erro ocorre quando algo se passa com a internet (por exemplo muda de móvel para wireless, ou vice versa, ou então quando o telemóvel se conecta a outro router na universidade). Apenas informa que algo aconteceu e a app está instável, por isso eu deveria fazer logout. Mas se eu escolher "no", então posso continuar usando normalmente...

**Comment by DarkLegend481** [comment]
@andremvm isso é normal, comigo acontece as vezes... Vai ver é um erro com a API...

**Comment by mtaheij** [comment]
I'm not sure what it is that is discussed here... It is an issue, are there still questions? Can it be closed? Please try to keep things in English (no matter if you use a translator)

**Comment by andremvm** [comment]
I think now it can be closed. It was about the error that sometimes pops saying that the app is unstable and you should logout. As I said from my experience, that only happens when there was something wrong with the internet (for example when I shift from wifi to celular data), and you can select "No" in the error message to make it go away...
