### ISSUE TITLE
No items or EXP for visiting PokeStop

### ISSUE THREAD

**Issue by Diagoras14** [mtaheij/PoGo-UWP#60]
Device info
------------------
- Phone type: Lumia 735
- App version: v1.3.2-beta

Steps to reproduce
----------------
Enter PokeStop.

Actual behavior
-----------------
No exp or items added for visiting PokeStop and it stays blue on map after closing window.

![17858794_1338697109510407_1233490043_o](https://cloud.githubusercontent.com/assets/27095051/24914541/cd5228a4-1ed4-11e7-8f2e-d95f2369ccec.jpg)

Expected behavior
---------------
PokeStop turns purple (not sure if thats purple), items are added to eq and you get probably 50 exp.

Other information
---------------
Worked fine until today.

**Comment by WanderingJesusFreak** [comment]
This is usually because you have to throw out some items. Is your backpack full?

**Comment by Diagoras14** [comment]
Yes, throwing out some items fixed the issue. Would be nice having a popup about full backpack. :)

**Comment by ntaheij** [comment]
This is also In the full app, but it is a idea
