### ISSUE TITLE
Project does not compile - Visual Studio 2017

### ISSUE THREAD

**Issue by BrazilianBug** [mtaheij/PoGo-UWP#63]
I use Visual Studio 2017, it always worked normally, however I am trying to compile the latest version of POGO and it is not working, I use the build only to be able to install the APP in Windows 10, the APPX direct simply does not install (for reasons I I do not know)

"The program" [10376] PokemonGo-UWP.exe: Tracking Program "was closed with code 0 (0x0).
The program "[10376] PokemonGo-UWP.exe" was closed with the code -1073741819 (0xc0000005) 'Access violation'.
Failed to activate the Windows Store application "c602d2cb-fdd8-4e41-b5a1-8f9a8a1f56c7_pydwv93pqj8h0! App" error "Windows was unable to communicate with the destination application." This usually indicates that the destination application process has been aborted. More information may be available in the Debug panel of the Output window (Debug-> Windows-> Output). "

**Comment by mtaheij** [comment]
What was the problem and how did you resolve it? Can be good to know when other people have the same issue.

**Comment by BrazilianBug** [comment]
I could not solve the problem, but I was able to install the application in Windows 10 without having to compile in Visual Studio, but unfortunately the app ignores the default location defined in the windows 10 "maps" application, so I can not use it, I do not know if this is Related to the installation be this way or if the application does not actually recognize the location of windows 10.
