### ISSUE TITLE
Still loading encounter screen

### ISSUE THREAD

**Issue by ntaheij** [mtaheij/PoGo-UWP#67]
Device info
------------------
- Phone type: Idk
- App version: 1.2.3

Steps to reproduce
----------------
Try to catch a pokemon

Actual behavior
-----------------
Game will say loading encounter for pokemon

Expected behavior
---------------
Loading will have a duration of 4 seconds and than you will be able to catch

Other information
---------------
Yes i updated ;)

**Comment by mtaheij** [comment]
This issue seems to be there on Wifi only.
You can try this as a remedy: Close the app, turn off Wifi and start the app again.
