### ISSUE TITLE
Next up

### ISSUE THREAD

**Issue by mtaheij** [mtaheij/PoGo-UWP#7]
Currently, I am working on a change that allows us to transfer multiple Pokemons at once.

**Comment by mtaheij** [comment]
This is done in the multitransfer branch now.
Will make a new release asap

**Comment by mtaheij** [comment]
This is fixed in the multitransfer branch.
I will make a release asap

**Comment by mtaheij** [comment]
Release is ready!

**Comment by andremvm** [comment]
I can confirm that it is working properly :)
