### ISSUE TITLE
Fix crash in System.Linq.Enumerable.Cast<System.__Canon>, line 0

### ISSUE THREAD

**Issue by mtaheij** [mtaheij/PoGo-UWP#71]
### Stacktrace ###

<pre>System.Linq.Enumerable.Cast<System;__Canon>;;0
PokemonGo_UWP.App;PokemonsInventory_CollectionChanged;E:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\App.xaml.cs;158
System.ComponentModel.PropertyChangingEventHandler;Invoke;;0
System.Collections.ObjectModel.ObservableCollection$1<System.Collections.Generic.KeyValuePair$2<PokemonGo_UWP.Utils.AchievementType,System.__Canon>>;OnCollectionChanged;E:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\Entities\ObservableCollectionPlus.cs;297
System.Collections.ObjectModel.ObservableCollectionPlus$1<System.__Canon>;RemoveItem;E:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\Entities\ObservableCollectionPlus.cs;217
PokemonGo_UWP.Utils.GameClient.<>c__DisplayClass206_0;<UpdateLocalInventory>b__0;E:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\Utils\GameClient.cs;1264
System.ComponentModel.PropertyChangingEventHandler;Invoke;;0
Template10.Common.DispatcherWrapper.<>c__DisplayClass13_0;<DispatchIdle>b__0;f:\dd\ndp\fxcore\src\System.Private.WinRTInterop.CoreLib\Interop\Interop.WinRT.cs;220
Windows.UI.Xaml.DragEventHandler;Invoke;;0
McgInterop.ReverseComSharedStubs;Proc_;;0
System.Runtime.ExceptionServices.ExceptionDispatchInfo;Throw;f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\Runtime\ExceptionServices\ExceptionDispatchInfo.cs;61
System.Runtime.CompilerServices.TaskAwaiter;ThrowForNonSuccess;f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs;187
System.Runtime.CompilerServices.TaskAwaiter;HandleNonSuccessAndDebuggerNotification;f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs;156
System.Runtime.CompilerServices.TaskAwaiter;ValidateEnd;f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs;128
System.Runtime.CompilerServices.TaskAwaiter;GetResult;f:\dd\ndp\fxcore\CoreRT\src\System.Private.Threading\src\System\Runtime\CompilerServices\TaskAwaiter.cs;113
Template10.Common.DispatcherWrapper.<Dispatch>d__8;MoveNext;;0
McgInterop.McgHelpers;ThrowFailed;e:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\obj\ARM\Release\ilc\intermediate\PokemonGo-UWP.McgInterop\Helpers.g.cs;8601
McgInterop.ComCallHelpers;ComCall__HRESULT;e:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\obj\ARM\Release\ilc\intermediate\PokemonGo-UWP.McgInterop\SharedStubs.g.cs;10471
McgInterop.ForwardComSharedStubs.Proc_<System;__Canon>;e:\Users\Michel\Source\Repos\PoGo-UWP\PokemonGo-UWP\obj\ARM\Release\ilc\intermediate\PokemonGo-UWP.McgInterop\SharedStubs.g.cs;608
Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule;CoreApplication_UnhandledErrorDetected;;0</pre>

### Reason ###

ArgumentNull_Generic
Arg_ParamName_Name, source. For more information, visit http://go.microsoft.com/fwlink/?LinkId=623485

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/512316/crash_reasons/166348688](https://rink.hockeyapp.net/manage/apps/512316/crash_reasons/166348688)

**Comment by mtaheij** [comment]
This error occurs when you have a live tile set up and transfer a Pokémon.
The CollectionChanged event will fire twice, one time for the remaining collection, once for the removed item.

**Comment by Retep2041** [comment]
Is the hockey app meant to do something because it leads me to a page that says "You are not a member or tester of any apps."

**Comment by mtaheij** [comment]
Yes, it provides me with stack traces and crash reports. When 5 or more similar crashes occur, HockeyApp will open an issue here, so I can look into it.
I hope to find enough information in these stack traces to get rid of the annoying error messages.

Problem is that it works fine on my devices (a programmers' standard excuse), so I do not have information on how the errors occur on other devices. HockeyApp should provide me more info on this.

**Comment by mtaheij** [comment]
@Retep2041 If you can send me your email address in PM, I can add you. May be it will be possible to further help if crashes are coupled to a single user...

**Comment by Retep2041** [comment]
Ok i sent my email through Discord.

**Comment by Retep2041** [comment]
So have any reports from my devices shown yet?

**Comment by mtaheij** [comment]
I'm sure the reports are there, but I cannot see any distinguished reports by your user. It would be nice to have that for multiple users, so I can ask users specific questions. Unfortunately, your user profile still doesn't point out any devices, nor any versions of the app you are using.
I don't have enough experience with HockeyApp yet to trace all errors, but at least I've been able to find a few.
