### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by Skyterix** [mtaheij/PoGo-UWP#75]
Device info
------------------
- Phone type: Lumia 532
- App version: 1.3.3

Can't login after update !

**Comment by mtaheij** [comment]
What's the error message?

**Comment by Skyterix** [comment]
The same as you enter the wrong login details.
I try to create new ptc account but still not working.
Before update every thing works.

**Comment by Rokuzer** [comment]
I see "failed parsing pokehash response headers" in L830 V1.3.3

**Comment by Skyterix** [comment]
I sew this for 2 h but now i just can't login

**Comment by mtaheij** [comment]
Can you uninstall 1.3.3, download and install 1.3.2 again? It will not force update, so when starting 1.3.2, choose NOT to download and update the new version

**Comment by Skyterix** [comment]
Display only white screen

**Comment by Skyterix** [comment]
Notification about update has no text on it and button too just empty.
When i click left button app updating so i clicked right button but display only white screen.

**Comment by Skyterix** [comment]
I am using polish language

**Comment by mtaheij** [comment]
I've seen the empty text, will be resolved in the next version (1.3.4)
Hopefully, the login error is fixed also.

**Comment by Skyterix** [comment]
close
